# data

In [1]:
import json
import os

def export_list_to_local(data_list: list, filename: str = "x.json"):
    """
    Toma una lista de diccionarios, la guarda localmente como un archivo JSON
    con el nombre 'filename' y luego la guarda en el directorio actual.
    """
    # Destino actual
    target_dir = os.getcwd()

    target_path = os.path.join(target_dir, filename)

    # Guardar archivo
    try:
        with open(target_path, 'w', encoding='utf-8') as f:
            json.dump(data_list, f, indent=2)

        print(f"✅ Archivo exportado exitosamente a: {target_path}")

    except TypeError as e:
        print(f"Error: La lista contiene datos no serializables a JSON.\nDetalle: {e}")
    except Exception as e:
        print(f"Error al exportar el archivo: {e}")

# --- Lista de entrada ---

L = [
  {
    "instruction": "Explain the concept of a Fourier Series and its primary purpose.",
    "context": "",
    "response": "A Fourier Series is an expansion of a periodic function into an infinite sum of sines and cosines. Its primary purpose is to decompose a complex periodic waveform (like a sound wave or an electrical signal) into its fundamental frequency and its harmonics. This decomposition is incredibly useful for signal analysis, solving differential equations, and understanding the frequency components of a system.",
    "category": "open_qa"
  },
  {
    "instruction": "Given the function $f(x) = x^3 - 6x^2 + 5$, find the critical points and determine if they are local maxima, minima, or saddle points.",
    "context": "Critical points occur where the first derivative $f'(x)$ is zero or undefined. The second derivative test, $f''(x)$, can be used to classify these points: if $f''(c) > 0$, it's a local minimum; if $f''(c) < 0$, it's a local maximum.",
    "response": "First, we find the first derivative: $f'(x) = 3x^2 - 12x$. To find critical points, we set $f'(x) = 0$:\n$3x^2 - 12x = 0 \\implies 3x(x - 4) = 0$.\nThe critical points are $x = 0$ and $x = 4$.\nNext, we find the second derivative: $f''(x) = 6x - 12$.\nNow we apply the second derivative test to each critical point:\n1. At $x = 0$: $f''(0) = 6(0) - 12 = -12$. Since $f''(0) < 0$, this is a local maximum.\n2. At $x = 4$: $f''(4) = 6(4) - 12 = 24 - 12 = 12$. Since $f''(4) > 0$, this is a local minimum.",
    "category": "closed_qa"
  },
  {
    "instruction": "What is the key difference between NP-hard and NP-complete problems in computational complexity theory?",
    "context": "",
    "response": "The key difference lies in their definitions and relationship to the class NP (Nondeterministic Polynomial time). \n- An **NP-hard** problem is at least as hard as the hardest problems in NP. It does not have to be in NP itself (i.e., it doesn't need to have a solution that is verifiable in polynomial time). Any problem in NP can be reduced to an NP-hard problem in polynomial time.\n- An **NP-complete** problem is a problem that is both NP-hard AND is also in the class NP. This means it is one of the hardest problems in NP, and its solutions can be verified quickly. Therefore, NP-complete problems are a subset of NP-hard problems.",
    "category": "open_qa"
  },
  {
    "instruction": "Summarize the 'curse of dimensionality' in the context of machine learning.",
    "context": "",
    "response": "The 'curse of dimensionality' refers to various problems that arise when analyzing and organizing data in high-dimensional spaces, where the number of features is very large. As the number of dimensions increases, the volume of the space grows exponentially, causing the available data to become sparse, making it difficult for algorithms to find statistically significant patterns and increasing the computational cost of processing.",
    "category": "summarization"
  },
  {
    "instruction": "From the following text, extract the definition of 'linear independence'.",
    "context": "In the theory of vector spaces, a set of vectors is said to be linearly dependent if at least one of the vectors in the set can be defined as a linear combination of the others. If no vector in the set can be written in this way, then the vectors are said to be linearly independent. This condition can be formally stated as: the only solution to the equation $c_1\\vec{v_1} + c_2\\vec{v_2} + \\dots + c_n\\vec{v_n} = \\vec{0}$ is the trivial solution where all scalars $c_i$ are zero.",
    "response": "{\n  \"definition\": \"A set of vectors is linearly independent if no vector in the set can be expressed as a linear combination of the other vectors, which means the only way to sum scalar multiples of the vectors to get the zero vector is if all the scalars are zero.\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Write a short creative paragraph describing the process of row reduction as a form of puzzle-solving.",
    "context": "",
    "response": "Solving a system of equations via row reduction felt less like algebra and more like archaeology. I started with the augmented matrix, a block of numbers as indecipherable as ancient stone. The first pivot was my chisel, used to carve away the excess below the leading one, revealing the first layer of the structure. Each elementary row operation—swapping rows, scaling, adding a multiple of one row to another—was a careful brushstroke, dusting away debris. With each step, the matrix simplified, its hidden triangular form emerging from the noise. The final back-substitution was like fitting the last, crucial piece into a complex puzzle, where suddenly the identities of $x$, $y$, and $z$ became clear, the mystery of their values finally unearthed.",
    "category": "creative_writing"
  },
  {
    "instruction": "Generate a list of common metrics used to evaluate the performance of a classification model.",
    "context": "",
    "response": "Here are several common metrics used to evaluate classification models:\n\n1.  **Accuracy:** The proportion of total predictions that were correct. It is a good starting point but can be misleading for imbalanced datasets.\n2.  **Precision:** The proportion of positive identifications that was actually correct. Formula: $TP / (TP + FP)$. It answers the question: 'Of all the times the model predicted positive, how often was it right?'\n3.  **Recall (Sensitivity):** The proportion of actual positives that was identified correctly. Formula: $TP / (TP + FN)$. It answers the question: 'Of all the actual positive cases, how many did the model find?'\n4.  **F1-Score:** The harmonic mean of Precision and Recall, providing a single score that balances both. It's useful when you need to find a balance between the two.\n5.  **ROC Curve (Receiver Operating Characteristic):** A plot of the True Positive Rate (Recall) against the False Positive Rate at various threshold settings.\n6.  **AUC (Area Under the Curve):** The area under the ROC curve. It provides an aggregate measure of performance across all possible classification thresholds, where a value of 1.0 represents a perfect model.",
    "category": "generation"
  },
  {
    "instruction": "What is the relationship between the derivative and the integral of a function as described by the Fundamental Theorem of Calculus?",
    "context": "",
    "response": "The Fundamental Theorem of Calculus establishes that differentiation and integration are inverse operations. It consists of two parts:\n\n1.  **Part 1 (The Derivative of an Integral):** If you define a function as the integral of another function $f(t)$ from a constant to a variable $x$, i.e., $F(x) = \\int_{a}^{x} f(t)\\,dt$, then the derivative of $F(x)$ is the original function $f(x)$.\n\n2.  **Part 2 (The Integral of a Derivative):** The definite integral of a function's derivative, $f'(x)$, from $a$ to $b$ is simply the net change in the original function $f(x)$ between those points, i.e., $\\int_{a}^{b} f'(x)\\,dx = f(b) - f(a)$.",
    "category": "open_qa"
  },
  {
    "instruction": "Classify the following ordinary differential equation as linear or nonlinear: $y'' + \\sin(y) = 0$.",
    "context": "A differential equation is linear if the dependent variable and all of its derivatives appear in a linear fashion (i.e., not multiplied together, raised to powers, or inside other functions).",
    "response": "The differential equation $y'' + \\sin(y) = 0$ is **nonlinear**. This is because the dependent variable $y$ appears inside the sine function, $\\sin(y)$, which is a nonlinear operation.",
    "category": "classification"
  },
  {
    "instruction": "Calculate the L2 norm (Euclidean norm) of the vector $\\vec{v} = (1, -2, 2)$.",
    "context": "",
    "response": "The L2 norm of a vector $\\vec{v} = (v_1, v_2, ..., v_n)$ is given by the formula $||\\vec{v}||_2 = \\sqrt{v_1^2 + v_2^2 + \\dots + v_n^2}$.\nFor the vector $\\vec{v} = (1, -2, 2)$, the norm is:\n$||\\vec{v}||_2 = \\sqrt{1^2 + (-2)^2 + 2^2} = \\sqrt{1 + 4 + 4} = \\sqrt{9} = 3$.",
    "category": "closed_qa"
  },
  {
    "instruction": "What is the meaning of the Kronecker delta, $\\delta_{ij}$?",
    "context": "",
    "response": "The Kronecker delta, denoted $\\delta_{ij}$, is a function of two variables (usually integers) that is defined to be 1 if the variables are equal, and 0 if they are not. Formally:\n$\\delta_{ij} = \\begin{cases} 1 & \\text{if } i=j \\\\ 0 & \\text{if } i \\neq j \\end{cases}$.\nIt is commonly used in linear algebra to represent the entries of the identity matrix and in tensor calculus to simplify expressions.",
    "category": "open_qa"
  },
  {
    "instruction": "Is the set of integers under the operation of multiplication a group? Explain why or why not.",
    "context": "For a set to be a group under an operation, it must satisfy four axioms: closure, associativity, the existence of an identity element, and the existence of an inverse for every element.",
    "response": "No, the set of integers ($\\\mathbb{Z}$) under multiplication is not a group. While it satisfies closure (integer * integer = integer), associativity, and has an identity element (1), it fails the inverse axiom. For most integers, their multiplicative inverse is not an integer. For example, the inverse of 2 is $1/2$, which is not in the set of integers. The only elements that have an integer inverse are 1 and -1. Since not every element has an inverse within the set, it is not a group.",
    "category": "open_qa"
  },
  {
    "instruction": "Generate an example of a 2x2 rotation matrix that rotates a point by $90^\\circ$ counterclockwise.",
    "context": "",
    "response": "A 2D counterclockwise rotation matrix is given by the formula:\n$R(\\theta) = \\begin{pmatrix} \\cos\\theta & -\\sin\\theta \\\\ \\sin\\theta & \\cos\\theta \\end{pmatrix}$.\nFor a rotation of $90^\\circ$, we have $\\theta = 90^\\circ$. We know that $\\cos(90^\\circ) = 0$ and $\\sin(90^\\circ) = 1$. Substituting these values into the matrix, we get:\n$R(90^\\circ) = \\begin{pmatrix} 0 & -1 \\\\ 1 & 0 \\end{pmatrix}$.",
    "category": "generation"
  },
  {
    "instruction": "What does it mean for a function to be 'analytic' in complex analysis?",
    "context": "",
    "response": "In complex analysis, a function is said to be analytic (or holomorphic) at a point if it is complex differentiable not only at that point but also in a neighborhood around that point. This is a much stronger condition than real differentiability. A key consequence is that if a function is analytic, it is infinitely differentiable and can be represented by a convergent Taylor series in that neighborhood.",
    "category": "open_qa"
  },
  {
    "instruction": "Summarize the Pigeonhole Principle.",
    "context": "",
    "response": "The Pigeonhole Principle states that if you have more items ('pigeons') than you have containers ('pigeonholes'), then at least one container must hold more than one item. Formally, if $n$ items are put into $m$ containers with $n > m$, then at least one container must contain more than one item.",
    "category": "summarization"
  },
  {
    "instruction": "Calculate the value of the binomial coefficient $\\binom{5}{2}$.",
    "context": "The binomial coefficient $\\binom{n}{k}$ is given by the formula $\\frac{n!}{k!(n-k)!}$.",
    "response": "Using the formula for the binomial coefficient with $n=5$ and $k=2$:\n$\\binom{5}{2} = \\frac{5!}{2!(5-2)!} = \\frac{5!}{2!3!}$\n$= \\frac{5 \\times 4 \\times 3 \\times 2 \\times 1}{(2 \\times 1)(3 \\times 2 \\times 1)} = \\frac{120}{2 \\times 6} = \\frac{120}{12} = 10$.",
    "category": "closed_qa"
  },
  {
    "instruction": "What is the primary motivation for using CUDA or OpenCL for computation?",
    "context": "",
    "response": "The primary motivation for using CUDA or OpenCL is to harness the massive parallel processing power of modern Graphics Processing Units (GPUs) for general-purpose computation, a practice known as GPGPU. GPUs contain thousands of simpler cores designed to perform the same operation on many different pieces of data simultaneously, making them exceptionally efficient for data-parallel tasks like scientific simulations, matrix operations, and machine learning, often providing orders-of-magnitude speedup over traditional CPUs.",
    "category": "open_qa"
  },
  {
    "instruction": "Classify the following functions based on their growth rate (e.g., logarithmic, linear, quadratic, exponential): $f(n) = n^2$, $g(n) = \\log(n)$, $h(n) = 2^n$, $k(n) = 3n + 5$.",
    "context": "",
    "response": "{\n  \"logarithmic\": \"$g(n) = \\log(n)$\",\n  \"linear\": \"$k(n) = 3n + 5$\",\n  \"quadratic\": \"$f(n) = n^2$\",\n  \"exponential\": \"$h(n) = 2^n$\"\n}",
    "category": "classification"
  },
  {
    "instruction": "From the text, extract the definition of a 'stochastic process'.",
    "context": "In probability theory, a stochastic process, or random process, is a mathematical object usually defined as a family of random variables. Historically, the random variables were associated with or indexed by a set of numbers, usually viewed as points in time, giving the interpretation of a stochastic process representing numerical values of some system randomly changing over time.",
    "response": "{\n  \"definition\": \"A stochastic process is a family or collection of random variables, typically indexed by time, that represents a system randomly changing over time.\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Brainstorm potential issues with using a very small learning rate in Gradient Descent.",
    "context": "",
    "response": "Using a very small learning rate in Gradient Descent can lead to several issues:\n\n1.  **Slow Convergence:** The primary issue is extremely slow convergence. The algorithm will take a huge number of tiny steps to reach a local minimum, making the training process computationally expensive and time-consuming.\n2.  **Getting Stuck in Local Minima:** In a non-convex loss landscape, a very small learning rate might cause the algorithm to get trapped in a poor local minimum or a saddle point, as it lacks the momentum to 'jump' out and explore other parts of the landscape.\n3.  **Inefficiency:** It makes the optimization process highly inefficient. While a large learning rate can cause overshooting and divergence, a tiny learning rate makes the process impractical for large datasets or complex models.",
    "category": "brainstorming"
  },
  {
    "instruction": "Write a short dialogue where two mathematicians argue about the beauty of pure vs. applied mathematics, using the Navier-Stokes equations as an example.",
    "context": "",
    "response": "**Dr. Anya Sharma (Pure Mathematician):** The Navier-Stokes equations are a monument to pure thought! The intricate dance of partial derivatives, the non-linear terms... their very existence and the challenge of proving their smooth solutions is a profound question of mathematical structure. It's beautiful.\n\n**Dr. Ben Carter (Applied Mathematician):** Beautiful? Anya, they're useful! Their beauty is in their power to describe the world. I see those equations and I see the swirl of a hurricane, the flow of blood through an artery, the airflow over a wing. They are a tool, a magnificent one, for predicting reality. What good is a 'smooth solution' if I can't use it to design a more efficient turbine?\n\n**Anya:** You see a tool; I see a truth waiting to be uncovered. The application is a fleeting, transient consequence. The underlying mathematical truth of the equations' structure is eternal. You're admiring the paint on the canvas; I'm admiring the canvas itself.",
    "category": "creative_writing"
  },
  {
    "instruction": "What is the expected value of a single roll of a standard six-sided die?",
    "context": "",
    "response": "The expected value $E(X)$ of a discrete random variable is the sum of each possible outcome multiplied by its probability. For a standard six-sided die, each outcome {1, 2, 3, 4, 5, 6} has a probability of $1/6$.\n$E(X) = (1 \\cdot \\frac{1}{6}) + (2 \\cdot \\frac{1}{6}) + (3 \\cdot \\frac{1}{6}) + (4 \\cdot \\frac{1}{6}) + (5 \\cdot \\frac{1}{6}) + (6 \\cdot \\frac{1}{6})$\n$E(X) = \\frac{1+2+3+4+5+6}{6} = \\frac{21}{6} = 3.5$.",
    "category": "closed_qa"
  },
  {
    "instruction": "Generate the first 5 terms of the Fibonacci sequence, starting with $F_0 = 0$ and $F_1 = 1$.",
    "context": "",
    "response": "The Fibonacci sequence is defined by the recurrence relation $F_n = F_{n-1} + F_{n-2}$, with initial values $F_0 = 0$ and $F_1 = 1$.\n- $F_0 = 0$\n- $F_1 = 1$\n- $F_2 = F_1 + F_0 = 1 + 0 = 1$\n- $F_3 = F_2 + F_1 = 1 + 1 = 2$\n- $F_4 = F_3 + F_2 = 2 + 1 = 3$\nThe first 5 terms are 0, 1, 1, 2, 3.",
    "category": "generation"
  },
  {
    "instruction": "What is the purpose of a 'hash function' in the context of a hash table?",
    "context": "",
    "response": "In a hash table, the purpose of a hash function is to compute an index, or a 'hash code', from a given key. This index is then used to determine where in the underlying array the value associated with that key should be stored or retrieved. An effective hash function distributes keys as evenly as possible across the array, which is crucial for achieving the hash table's primary benefit: average-case constant time complexity, $O(1)$, for insertions, deletions, and lookups.",
    "category": "open_qa"
  },
  {
    "instruction": "Summarize the 'Singular Value Decomposition' (SVD) of a matrix.",
    "context": "",
    "response": "Singular Value Decomposition (SVD) is a factorization of a real or complex matrix that generalizes the eigendecomposition. It states that any matrix $A$ can be decomposed into the product of three other matrices: $A = U\\Sigma V^T$, where $U$ and $V$ are orthogonal matrices and $\\Sigma$ is a diagonal matrix of non-negative 'singular values'. SVD is a powerful technique used in many applications, including dimensionality reduction, data compression, and calculating the pseudoinverse of a matrix.",
    "category": "summarization"
  },
  {
    "instruction": "Classify the problem of determining the optimal route for a delivery truck to visit a set of cities and return to the origin.",
    "context": "",
    "response": "This is a classic example of the **Traveling Salesperson Problem (TSP)**, which is a well-known problem in **combinatorial optimization**. It is considered NP-hard, meaning there is no known efficient algorithm to find the optimal solution for all cases, especially as the number of cities grows.",
    "category": "classification"
  },
  {
    "instruction": "Find the inverse of the 2x2 matrix $A = \\begin{pmatrix} 4 & 7 \\\\ 2 & 6 \\end{pmatrix}$.",
    "context": "The inverse of a 2x2 matrix $\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}$ is given by $\\frac{1}{ad-bc} \\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix}$.",
    "response": "First, we calculate the determinant of the matrix: $\\det(A) = ad-bc = (4)(6) - (7)(2) = 24 - 14 = 10$.\nSince the determinant is non-zero, the inverse exists.\nNow, we apply the formula for the inverse:\n$A^{-1} = \\frac{1}{10} \\begin{pmatrix} 6 & -7 \\\\ -2 & 4 \\end{pmatrix}$\n$= \\begin{pmatrix} 6/10 & -7/10 \\\\ -2/10 & 4/10 \\end{pmatrix} = \\begin{pmatrix} 3/5 & -7/10 \\\\ -1/5 & 2/5 \\end{pmatrix}$.",
    "category": "closed_qa"
  },
  {
    "instruction": "What is the difference between a 'greedy algorithm' and 'dynamic programming'?",
    "context": "",
    "response": "Both greedy algorithms and dynamic programming are optimization techniques, but they differ in their approach.\n\n- A **greedy algorithm** makes the locally optimal choice at each step with the hope of finding a global optimum. It does not reconsider its choices. This approach is simple and fast but does not guarantee a globally optimal solution for all problems.\n\n- **Dynamic programming** breaks down a problem into smaller, overlapping subproblems. It solves each subproblem only once and stores its solution in a table (memoization or tabulation) to avoid re-computation. By combining the solutions to the subproblems, it finds the globally optimal solution for the main problem. It is generally more complex but guarantees optimality if the problem has optimal substructure and overlapping subproblems.",
    "category": "open_qa"
  },
  {
    "instruction": "From the following text, what is the role of the 'objective function' in an optimization problem?",
    "context": "An optimization problem consists of maximizing or minimizing a real function by systematically choosing input values from within an allowed set. This function, which is to be minimized or maximized, is referred to as the objective function. The set of allowed input values is defined by a set of constraints.",
    "response": "{\n  \"role\": \"The objective function is the real function in an optimization problem that one seeks to either maximize or minimize.\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Generate a list of five famous unsolved problems in mathematics.",
    "context": "",
    "response": "Here are five famous unsolved problems in mathematics:\n\n1.  **The Riemann Hypothesis:** Concerns the distribution of prime numbers. It conjectures that all non-trivial zeros of the Riemann zeta function have a real part of $1/2$.\n2.  **The Collatz Conjecture (or $3n+1$ problem):** A simple sequence where you take any positive integer $n$. If $n$ is even, divide it by 2. If $n$ is odd, multiply it by 3 and add 1. The conjecture is that this process will eventually reach the number 1, regardless of which positive integer was chosen initially.\n3.  **The Goldbach Conjecture:** States that every even integer greater than 2 is the sum of two prime numbers.\n4.  **The Twin Prime Conjecture:** Posits that there are infinitely many pairs of prime numbers that differ by 2 (e.g., 3 and 5, 11 and 13).\n5.  **P vs NP Problem:** A major unsolved problem in computer science. It asks whether every problem whose solution can be quickly verified by a computer can also be quickly solved by a computer.",
    "category": "generation"
  },
  {
    "instruction": "What is Euler's Identity and why is it considered beautiful?",
    "context": "",
    "response": "Euler's Identity is the equation $e^{i\\pi} + 1 = 0$. It is widely considered beautiful by mathematicians because it elegantly and concisely connects five of the most fundamental constants in mathematics: \n- $e$, the base of natural logarithms.\n- $i$, the imaginary unit, which satisfies $i^2 = -1$.\n- $\\pi$, the ratio of a circle's circumference to its diameter.\n- $1$, the multiplicative identity.\n- $0$, the additive identity.\nThe identity links these disparate fields of mathematics (analysis, algebra, and geometry) into one simple, profound relationship.",
    "category": "open_qa"
  },
  {
    "instruction": "Classify the conic section represented by the equation $4x^2 - 9y^2 = 36$.",
    "context": "",
    "response": "To classify the conic section, we can rewrite the equation in standard form by dividing by 36:\n$\\frac{4x^2}{36} - \\frac{9y^2}{36} = 1$\n$\\frac{x^2}{9} - \\frac{y^2}{4} = 1$\nThis equation is in the standard form $\\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1$, which represents a **hyperbola**.",
    "category": "classification"
  },
  {
    "instruction": "Write a short paragraph explaining the concept of a fractal in a creative and accessible way.",
    "context": "",
    "response": "Imagine a coastline drawn on a map. From a distance, it has a certain jagged shape. But as you zoom in on any small section, you don't find a straight line; instead, you find more jaggedness that looks remarkably similar to the original, larger coastline. Zoom in again, and the pattern repeats. This is the essence of a fractal: a never-ending pattern that is self-similar across different scales. It's a shape built from simple rules repeated infinitely, creating a structure of mesmerizing, infinite complexity from utter simplicity, just like a tree where every branch gives way to smaller branches that echo the form of the whole tree.",
    "category": "creative_writing"
  },
  {
    "instruction": "What is the power set of the set $S = \\{a, b\\}$?",
    "context": "",
    "response": "The power set of a set is the set of all its subsets, including the empty set and the set itself. For $S = \\{a, b\\}$, the subsets are:\n- The empty set: $\\emptyset$\n- Subsets with one element: $\\{a\\}, \\{b\\}$\n- The set itself: $\\{a, b\\}$\nTherefore, the power set is $P(S) = \\{\\emptyset, \\{a\\}, \\{b\\}, \\{a, b\\}\\}$.",
    "category": "closed_qa"
  },
  {
    "instruction": "Summarize the concept of 'backpropagation' in neural networks.",
    "context": "",
    "response": "Backpropagation is the primary algorithm used for training artificial neural networks. It works by first calculating the loss (error) between the network's predicted output and the actual output, and then propagating this error backward through the network, from the output layer to the input layer. During this backward pass, it uses the chain rule of calculus to calculate the gradient of the loss function with respect to each weight and bias in the network, and these gradients are then used by an optimization algorithm, like gradient descent, to update the parameters and improve the network's accuracy.",
    "category": "summarization"
  },
  {
    "instruction": "From the provided context, extract the purpose of an 'MPI communicator'.",
    "context": "In the Message Passing Interface (MPI), communication operations always happen within a specific group of processes. An MPI communicator is an object that defines this group of processes and provides a safe communication context for them. This means that messages sent within one communicator will not be accidentally received by processes in a different communicator, allowing for the organization of parallel computations into isolated, logical groups.",
    "response": "{\n  \"purpose\": \"An MPI communicator defines a group of processes and creates a safe, isolated communication context for them, ensuring that messages are only exchanged among the members of that specific group.\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Generate the truth table for the logical operation $P \\land (P \\to Q)$.",
    "context": "",
    "response": "To generate the truth table, we first need the table for $P \\to Q$ (P implies Q), which is only false when P is true and Q is false. Then we compute the AND ($$\\land$$) operation.\n\n| P | Q | $P \\to Q$ | $P \\land (P \\to Q)$ |\n|---|---|---|---|\n| T | T | T | T |\n| T | F | F | F |\n| F | T | T | F |\n| F | F | T | F |",
    "category": "generation"
  },
  {
    "instruction": "What is the difference between an 'analytic solution' and a 'numerical solution' for a differential equation?",
    "context": "",
    "response": "An **analytic solution** is an exact, closed-form expression or formula that describes the behavior of the solution for all values in its domain. It is found using symbolic manipulation and integration techniques. For example, the solution to $y' = y$ is $y(t) = Ce^t$.\n\nA **numerical solution**, on the other hand, is an approximation of the solution at a discrete set of points. It is found using algorithms (like Euler's method or Runge-Kutta methods) that start from an initial condition and step forward in time or space to approximate the solution's values. It provides a set of numbers, not a formula, and is used when an analytic solution is impossible or too difficult to find.",
    "category": "open_qa"
  },
  {
    "instruction": "What is the value of the imaginary unit $i$ raised to the power of 10? ($i^{10}$)",
    "context": "",
    "response": "The powers of the imaginary unit $i$ cycle in a pattern of four: $i^1 = i$, $i^2 = -1$, $i^3 = -i$, $i^4 = 1$. To find the value of $i^{10}$, we can use this pattern. We can divide the exponent by 4 and look at the remainder.\n$10 \\div 4 = 2$ with a remainder of 2.\nSo, $i^{10} = (i^4)^2 \\cdot i^2 = (1)^2 \\cdot (-1) = -1$.",
    "category": "closed_qa"
  },
  {
    "instruction": "Brainstorm the steps you would take to prove that $\\sqrt{2}$ is irrational.",
    "context": "",
    "response": "The classic way to prove that $\\sqrt{2}$ is irrational is by using a proof by contradiction. Here are the steps:\n\n1.  **Assume the Opposite:** Start by assuming that $\\sqrt{2}$ is rational. By definition, this means it can be written as a fraction $\\frac{p}{q}$ where $p$ and $q$ are integers with no common factors (i.e., the fraction is in its simplest form) and $q \\neq 0$.\n2.  **Set up the Equation:** Write the equation $\\sqrt{2} = \\frac{p}{q}$.\n3.  **Algebraic Manipulation:** Square both sides to get $2 = \\frac{p^2}{q^2}$, which can be rearranged to $p^2 = 2q^2$.\n4.  **Deduce Properties of p:** This equation shows that $p^2$ is an even number. If a square is even, the number itself must also be even. Therefore, $p$ is even. This means we can write $p = 2k$ for some integer $k$.\n5.  **Substitute and Deduce Properties of q:** Substitute $p=2k$ back into the equation $p^2 = 2q^2$. This gives $(2k)^2 = 2q^2$, which simplifies to $4k^2 = 2q^2$, and further to $q^2 = 2k^2$. This shows that $q^2$ is also an even number, which implies that $q$ must also be even.\n6.  **Find the Contradiction:** We have deduced that both $p$ and $q$ are even. This means they share a common factor of 2. However, this contradicts our initial assumption that the fraction $\\frac{p}{q}$ was in its simplest form with no common factors.\n7.  **Conclude:** Since our initial assumption leads to a logical contradiction, the assumption must be false. Therefore, $\\sqrt{2}$ cannot be rational and must be irrational.",
    "category": "brainstorming"
  },
  {
    "instruction": "Classify the point $(0,0)$ for the function $f(x, y) = x^2 - y^2$.",
    "context": "",
    "response": "To classify the critical point $(0,0)$, we use the second derivative test for multivariable functions. First, we find the partial derivatives:\n$f_x = 2x$, $f_y = -2y$\n$f_{xx} = 2$, $f_{yy} = -2$, $f_{xy} = 0$\nThe discriminant is $D(x,y) = f_{xx}f_{yy} - (f_{xy})^2$.\nAt $(0,0)$, $D(0,0) = (2)(-2) - (0)^2 = -4$.\nSince $D < 0$, the point $(0,0)$ is a **saddle point**.",
    "category": "classification"
  },
  {
    "instruction": "What is the relationship between the number of edges and vertices in a tree (a connected acyclic graph)?",
    "context": "",
    "response": "In any tree (a connected graph with no cycles), there is a simple and fundamental relationship between the number of vertices ($V$) and the number of edges ($E$). A tree with $V$ vertices always has exactly $E = V - 1$ edges.",
    "category": "open_qa"
  },
  {
    "instruction": "Summarize the purpose of Principal Component Analysis (PCA).",
    "context": "",
    "response": "Principal Component Analysis (PCA) is a statistical technique used for dimensionality reduction that transforms a set of possibly correlated variables into a smaller set of linearly uncorrelated variables called principal components. Its main purpose is to simplify complex datasets by capturing the maximum amount of variance with the fewest components, making the data easier to visualize and analyze while retaining most of its important information.",
    "category": "summarization"
  },
  {
    "instruction": "Write a short creative story about a character who lives in a world based on the axioms of Zermelo-Fraenkel set theory.",
    "context": "",
    "response": "Elara lived in a world of pure logic, governed by the Axioms. Her existence began with the Axiom of the Empty Set; she was born from nothing. Then, through the Axiom of Pairing, she was paired with her Guardian, creating the first set of two. Her world expanded with the Axiom of Union, as her family set was united with others, forming a community. She learned that she could never contain herself—the Axiom of Regularity forbade it, preventing strange loops of existence. Her greatest desire was to choose one perfect moment from each day of her life, but the Axiom of Choice, though powerful and accepted by the leaders, always felt like an article of faith. It promised the existence of a set containing one moment from each day, a perfect timeline of happiness, but it never told her how to construct it. She was a well-defined set, existing in a universe of infinite unions, but the perfect life, she realized, was a choice whose existence was merely guaranteed, never shown.",
    "category": "creative_writing"
  },
  {
    "instruction": "From the following text, what is the 'kernel' of a linear transformation?",
    "context": "In algebra, a linear transformation is a function between two vector spaces that preserves the operations of vector addition and scalar multiplication. For a linear transformation $T: V \\to W$, the set of all vectors in the domain $V$ that are mapped to the zero vector in the codomain $W$ is a crucial subspace. This subspace is known as the kernel or null space of the transformation.",
    "response": "{\n  \"definition\": \"The kernel of a linear transformation is the set of all vectors in the domain that are mapped to the zero vector in the codomain.\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Generate the power set of $A = \\{1, 2, 3\\}$.",
    "context": "",
    "response": "The power set of $A$ is the set of all its subsets.\n- Empty set: $\\emptyset$\n- Subsets of size 1: $\\{1\\}, \\{2\\}, \\{3\\}$\n- Subsets of size 2: $\\{1, 2\\}, \\{1, 3\\}, \\{2, 3\\}$\n- Subset of size 3: $\\{1, 2, 3\\}$\n\nThe complete power set is $P(A) = \\{\\emptyset, \\{1\\}, \\{2\\}, \\{3\\}, \\{1, 2\\}, \\{1, 3\\}, \\{2, 3\\}, \\{1, 2, 3\\}\\}$. It contains $2^3 = 8$ elements.",
    "category": "generation"
  },
  {
    "instruction": "What is the meaning of the notation $O(n^2)$ (Big O notation)?",
    "context": "",
    "response": "The notation $O(n^2)$, read as 'Big O of n squared', describes the upper bound on the time complexity or space complexity of an algorithm. It means that as the size of the input, $n$, grows, the algorithm's runtime or memory usage will grow at most quadratically with respect to $n$. For a sufficiently large $n$, the runtime will be less than some constant multiplied by $n^2$. This is also referred to as quadratic time complexity.",
    "category": "open_qa"
  },
  {
    "instruction": "Calculate the probability of drawing an Ace from a standard 52-card deck.",
    "context": "",
    "response": "A standard deck of 52 cards has 4 Aces. The probability of an event is the number of favorable outcomes divided by the total number of possible outcomes.\n$P(Ace) = \\frac{\\text{Number of Aces}}{\\text{Total Number of Cards}} = \\frac{4}{52}$.\nThis fraction simplifies to $\\frac{1}{13}$.",
    "category": "closed_qa"
  }
]

<>:98: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
<>:98: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
C:\Users\isadmin\AppData\Local\Temp\ipykernel_10176\807379726.py:98: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
  "response": "No, the set of integers ($\\\mathbb{Z}$) under multiplication is not a group. While it satisfies closure (integer * integer = integer), associativity, and has an identity element (1), it fails the inverse axiom. For most integers, their multiplicative inverse is not an integer. For example, the inverse of 2 is $1/2$, which is not in the set of integers. The only elements that have an integer inverse are 1 and -1. Since not every element has an inverse within the set, it is not a group.",

### a lot of extensios ... more maths + more physics

In [2]:
F=[
    {
      "instruction": "Explain the concept of 'overfitting' in the context of Decision Trees and how 'pruning' addresses it.",
      "context": "Block 1: Data - Topic 2: Decision Trees (Sobreentrenamiento y poda).",
      "response": "Overfitting occurs when a decision tree becomes too complex, learning the noise in the training data rather than the underlying pattern. This results in perfect performance on training data but poor generalization to new, unseen data. **Pruning** is a technique used to reduce the size of the tree by removing sections (sub-trees) that provide little power to classify instances. Pre-pruning stops the tree construction early (e.g., by setting a threshold for information gain), while post-pruning removes branches from a fully grown tree.",
      "category": "open_qa"
    },
    {
      "instruction": "Calculate the 'Entropy' of a set $S$ containing 10 examples, where 6 are positive and 4 are negative.",
      "context": "Block 1: Data - Topic 2: Decision Trees (Algoritmo ID3).",
      "response": "The formula for Entropy is $H(S) = -p_+ \\log_2(p_+) - p_- \\log_2(p_-)$.\nHere, $p_+ = \\frac{6}{10} = 0.6$ and $p_- = \\frac{4}{10} = 0.4$.\n$H(S) = -0.6 \\log_2(0.6) - 0.4 \\log_2(0.4)$\nUsing $\\log_2(0.6) \\approx -0.737$ and $\\log_2(0.4) \\approx -1.322$:\n$H(S) \\approx -0.6(-0.737) - 0.4(-1.322)$\n$H(S) \\approx 0.4422 + 0.5288$\n$H(S) \\approx 0.971$.\nThe entropy is approximately 0.971 bits.",
      "category": "closed_qa"
    },
    {
      "instruction": "Summarize the 'Sequential Covering Algorithm' used for classification rules.",
      "context": "Block 1: Data - Topic 4: Classification Rules (Algoritmo de recubrimiento secuencial).",
      "response": "The Sequential Covering Algorithm is a method for extracting a set of classification rules from data. It works iteratively by learning one rule at a time that has high accuracy. Once a rule is found, all training examples covered by that rule are removed from the dataset. This process repeats with the remaining data until all positive examples are covered or a stopping criterion is met. It essentially 'covers' the dataset slice by slice with specific rules.",
      "category": "summarization"
    },
    {
      "instruction": "From the text, what is the 'Kappa Statistic' used for?",
      "context": "Block 1: Data - Topic 3: Evaluation of Classifiers (Estadístico de Kappa).",
      "response": "{\n  \"definition\": \"The Kappa statistic is a metric used to evaluate classifiers by measuring the agreement between the predicted and actual classifications, while correcting for the agreement that could occur by chance. It provides a more robust measure than simple accuracy, especially for imbalanced datasets.\"\n}",
      "category": "information_extraction"
    },
    {
      "instruction": "Classify the following variables as 'Continuous' or 'Categorical': Temperature (in Kelvin), Zip Code, Color of a Quark, Electron Voltage.",
      "context": "Block 1: Data - Topic 1: Exploration and processing of data.",
      "response": "{\n  \"Continuous\": [\n    \"Temperature (in Kelvin)\",\n    \"Electron Voltage\"\n  ],\n  \"Categorical\": [\n    \"Zip Code (Nominal)\",\n    \"Color of a Quark (Nominal)\"\n  ]\n}",
      "category": "classification"
    },
    {
      "instruction": "Brainstorm visualization techniques for high-dimensional data reduction.",
      "context": "Block 1: Data - Topic 1: Introduction to multivariate analysis and dimensionality reduction.",
      "response": "1. **Principal Component Analysis (PCA):** Projecting data onto orthogonal axes that maximize variance.\n2. **t-SNE (t-Distributed Stochastic Neighbor Embedding):** Non-linear technique good for visualizing clusters in 2D or 3D.\n3. **UMAP (Uniform Manifold Approximation and Projection):** Preserves both local and global structure better than t-SNE.\n4. **Parallel Coordinates:** Plotting multivariate data as lines across parallel axes.\n5. **Autoencoders:** Using neural networks to compress input into a lower-dimensional latent space.",
      "category": "brainstorming"
    },
    {
      "instruction": "Write a short creative story about a data point being processed by the ID3 algorithm.",
      "context": "Block 1: Data - Topic 2: ID3 Algorithm.",
      "response": "I was Row 452, a vector of attributes floating in the dataset void. My features—'Sunny', 'Hot', 'High Humidity'—were my identity. Suddenly, the Great Divider, ID3, approached. It wielded the Scythe of Entropy. 'To maximize Information Gain,' it thundered, 'I must split you based on Humidity!' I felt a tear as I was separated from my 'Normal Humidity' brethren. I slid down the 'High' branch, trembling. At the next node, the Wind attribute inspected me. 'Weak,' I confessed. 'Then you are a leaf,' the tree decided. 'Your label is No.' I had been classified. My journey was over.",
      "category": "creative_writing"
    },
    {
      "instruction": "Generate the formula for the 'Gini Impurity' index.",
      "context": "Block 1: Data - Topic 2: Decision Trees (Evaluation metrics similar to Entropy).",
      "response": "The Gini Impurity for a set of items with $J$ classes, where $p_i$ is the probability of an item belonging to class $i$, is given by:\n$Gini = 1 - \\sum_{i=1}^{J} p_i^2$.",
      "category": "generation"
    },
    {
      "instruction": "Explain the role of the 'Activation Function' in a neural network.",
      "context": "Block 2: Data Management Systems - Topic 5: Neural Networks (Conceptos básicos).",
      "response": "The activation function introduces non-linearity into the neural network. Without it, a neural network, no matter how many layers it has, would behave just like a single-layer linear perceptron (since a composition of linear functions is just another linear function). Common activation functions include the Sigmoid ($ \\sigma(x) = \\frac{1}{1+e^{-x}} $), ReLU ($ f(x) = \\max(0, x) $), and Tanh. They decide whether a neuron should be activated or not based on the weighted sum of the inputs.",
      "category": "open_qa"
    },
    {
      "instruction": "Calculate the output of a single neuron with inputs $x_1=0.5, x_2=-1$, weights $w_1=2, w_2=3$, bias $b=-1$, using a ReLU activation function.",
      "context": "Block 2: Data Management Systems - Topic 5: Neural Networks (Redes de neuronas simples).",
      "response": "First, we calculate the weighted sum $z$:\n$z = (w_1 \\cdot x_1) + (w_2 \\cdot x_2) + b$\n$z = (2 \\cdot 0.5) + (3 \\cdot -1) + (-1)$\n$z = 1 - 3 - 1 = -3$\nNow, we apply the ReLU activation function $f(z) = \\max(0, z)$:\n$output = \\max(0, -3) = 0$.\nThe output of the neuron is 0.",
      "category": "closed_qa"
    },
    {
      "instruction": "Summarize the 'Expectation-Maximization' (EM) algorithm in the context of clustering.",
      "context": "Block 2: Data Management Systems - Topic 7: Clustering (Algoritmo EM).",
      "response": "The Expectation-Maximization (EM) algorithm is an iterative method used to find maximum likelihood estimates of parameters in statistical models, often used for Gaussian Mixture Models (GMM) in clustering. It consists of two steps: the **E-step** (Expectation), where it creates a function for the expectation of the log-likelihood using the current estimate for the parameters (assigning probabilities of data points belonging to clusters), and the **M-step** (Maximization), where it computes parameters maximizing the expected log-likelihood found on the E-step. These steps repeat until convergence.",
      "category": "summarization"
    },
    {
      "instruction": "From the text, what is the main difference between 'Simple Linear Regression' and 'Logistic Regression'?",
      "context": "Block 2: Data Management Systems - Topic 6: Regression Models.",
      "response": "{\n  \"Simple Linear Regression\": \"Predicts a continuous output variable ($y$) based on an input variable ($x$) assuming a linear relationship ($y = mx + b$).\",\n  \"Logistic Regression\": \"Used for classification problems where the output is categorical (often binary). It uses the logistic function to model the probability that an instance belongs to a particular class, outputting values between 0 and 1.\"\n}",
      "category": "information_extraction"
    },
    {
      "instruction": "Classify the following algorithms as 'Supervised Learning' or 'Unsupervised Learning': K-Means, Backpropagation Neural Network, Support Vector Machine (SVM), Hierarchical Clustering.",
      "context": "Block 2: Data Management Systems - Topics 5, 6, 7.",
      "response": "{\n  \"Supervised Learning\": [\n    \"Backpropagation Neural Network\",\n    \"Support Vector Machine (SVM)\"\n  ],\n  \"Unsupervised Learning\": [\n    \"K-Means\",\n    \"Hierarchical Clustering\"\n  ]\n}",
      "category": "classification"
    },
    {
      "instruction": "Brainstorm potential applications of Recurrent Neural Networks (RNNs) in Physics.",
      "context": "Block 2: Data Management Systems - Topic 5: Introduction to RNNs.",
      "response": "1. **Time-series forecasting:** Predicting chaotic systems like weather patterns or fluid dynamics turbulence over time.\n2. **Particle Trajectory Prediction:** Analyzing sequences of detector hits to reconstruct particle tracks in high-energy physics experiments.\n3. **Quantum Control:** Optimizing pulse sequences for qubit manipulation by learning temporal dependencies.\n4. **Event Classification:** Identifying rare astrophysical events (like gravitational waves) in continuous data streams.\n5. **Material Degradation:** predicting the fatigue life of materials based on historical stress-strain data sequences.",
      "category": "brainstorming"
    },
    {
      "instruction": "Write a short creative dialogue between a Linear Regression model and a Neural Network.",
      "context": "Block 2: Data Management Systems - Topics 5 & 6.",
      "response": "**Linear Regression:** \"Why are you so complicated? I draw a straight line. It's elegant. $y = mx + c$. Simple.\"\n**Neural Network:** \"Life isn't a straight line, my friend. It's a non-linear manifold. I have layers. I have depth.\"\n**Linear Regression:** \"You have overfitting! You hallucinate patterns in the noise. I offer interpretability.\"\n**Neural Network:** \"And I offer accuracy on the ImageNet dataset. Can you distinguish a cat from a dog with a single slope? I didn't think so.\"",
      "category": "creative_writing"
    },
    {
      "instruction": "Generate the cost function for Logistic Regression.",
      "context": "Block 2: Data Management Systems - Topic 6: Logistic Regression.",
      "response": "The cost function $J(\\theta)$ for logistic regression (binary cross-entropy) is:\n$J(\\theta) = -\\frac{1}{m} \\sum_{i=1}^{m} [y^{(i)} \\log(h_\\theta(x^{(i)})) + (1 - y^{(i)}) \\log(1 - h_\\theta(x^{(i)}))]$,\nwhere $m$ is the number of training examples, $y^{(i)}$ is the actual label, and $h_\\theta(x^{(i)})$ is the predicted probability.",
      "category": "generation"
    },
    {
      "instruction": "Explain the concept of 'Superposition' in the context of a Qubit.",
      "context": "Block 3: Quantum Computing - Topic 9: The physical qubit.",
      "response": "Unlike a classical bit that must be either 0 or 1, a qubit can exist in a linear combination of both states simultaneously. This is known as superposition. Mathematically, a pure qubit state $|\\psi\\rangle$ is represented as $|\\psi\\rangle = \\alpha|0\\rangle + \\beta|1\\rangle$, where $\\alpha$ and $\\beta$ are complex numbers satisfying the normalization condition $|\\alpha|^2 + |\\beta|^2 = 1$. Upon measurement, the qubit collapses to state $|0\\rangle$ with probability $|\\alpha|^2$ or state $|1\\rangle$ with probability $|\\beta|^2$.",
      "category": "open_qa"
    },
    {
      "instruction": "If a qubit is in the state $|\\psi\\rangle = \\frac{1}{\\sqrt{2}}|0\\rangle + \\frac{i}{\\sqrt{2}}|1\\rangle$, what is the probability of measuring the state $|1\\rangle$?",
      "context": "Block 3: Quantum Computing - Topic 9: Qubit as a two-level system.",
      "response": "The probability of measuring state $|1\\rangle$ is given by the squared magnitude of its amplitude coefficient $\\beta$.\nHere, $\\beta = \\frac{i}{\\sqrt{2}}$.\n$P(1) = |\\beta|^2 = |\\frac{i}{\\sqrt{2}}|^2 = (\\frac{i}{\\sqrt{2}})(\\frac{-i}{\\sqrt{2}})$\n$P(1) = \\frac{-i^2}{2} = \\frac{-(-1)}{2} = \\frac{1}{2}$.\nThe probability is 0.5 or 50%.",
      "category": "closed_qa"
    },
    {
      "instruction": "Summarize Shor's Algorithm and its significance.",
      "context": "Block 3: Quantum Computing - Topic 11: Quantum Algorithms (Algoritmo de Shor).",
      "response": "Shor's Algorithm is a quantum algorithm capable of factoring large integers exponentially faster than the best-known classical algorithms. It utilizes the Quantum Fourier Transform and period finding to solve the factorization problem. Its significance lies in its potential to break the RSA encryption scheme, which is widely used for securing data transmission and relies on the computational difficulty of factoring large numbers.",
      "category": "summarization"
    },
    {
      "instruction": "From the text, what defines the 'Adiabatic Quantum Computing' paradigm?",
      "context": "Block 3: Quantum Computing - Topic 10: Paradigms (Computación cuántica adiabática).",
      "response": "{\n  \"definition\": \"Adiabatic Quantum Computing relies on the adiabatic theorem. The system starts in the ground state of a simple, known Hamiltonian and is slowly evolved to the ground state of a complex Hamiltonian that encodes the solution to the problem. If the evolution is slow enough, the system remains in the ground state throughout the process.\"\n}",
      "category": "information_extraction"
    },
    {
      "instruction": "Classify the following gates as 'Single-Qubit Gates' or 'Multi-Qubit Gates': Hadamard (H), CNOT, Pauli-X, Toffoli.",
      "context": "Block 3: Quantum Computing - Topic 10: Gate-based quantum computing.",
      "response": "{\n  \"Single-Qubit Gates\": [\n    \"Hadamard (H)\",\n    \"Pauli-X\"\n  ],\n  \"Multi-Qubit Gates\": [\n    \"CNOT (Controlled-NOT)\",\n    \"Toffoli (CCNOT)\"\n  ]\n}",
      "category": "classification"
    },
    {
      "instruction": "Brainstorm problems that can be mapped to the 'Ising Model' for quantum optimization.",
      "context": "Block 3: Quantum Computing - Topic 12: Quantum Optimization (Modelo de Ising).",
      "response": "1. **Portfolio Optimization:** Selecting a set of assets to maximize return for a given risk.\n2. **Traffic Flow Optimization:** Controlling traffic lights to minimize congestion in a city network.\n3. **Protein Folding:** Determining the lowest energy configuration of a protein chain.\n4. **Graph Partitioning:** Splitting a graph into subgraphs to minimize edges crossing between them.\n5. **Supply Chain Logistics:** Optimizing delivery routes and warehouse locations (related to Traveling Salesperson Problem).",
      "category": "brainstorming"
    },
    {
      "instruction": "Write a short creative story about a Qubit traversing the Bloch Sphere.",
      "context": "Block 3: Quantum Computing - Topic 9: The Qubit model.",
      "response": "Qubie started at the North Pole, the state of pure $|0\\rangle$. It was cold and deterministic there. Suddenly, a Hadamard wind blew, rotating Qubie $\\pi$ around the Y-axis and then around the Z-axis. Qubie found itself at the equator, lying on the X-axis. 'I am $|+\\rangle$!' Qubie shouted, feeling the thrill of superposition. 'I am both up and down!' But then, the ominous shadow of the Measurement Operator approached. 'Choose!' it demanded. Qubie panicked, spinning wildly along the azimuth. The environment decohered. With a sigh, Qubie collapsed back to the North Pole. 'Next time,' Qubie thought, 'I'll visit the South Pole.'",
      "category": "creative_writing"
    },
    {
      "instruction": "Generate the matrix representation of the Hadamard Gate.",
      "context": "Block 3: Quantum Computing - Topic 10: Quantum Gates.",
      "response": "The Hadamard gate $H$ is represented by the following $2 \\times 2$ matrix:\n$H = \\frac{1}{\\sqrt{2}} \\begin{pmatrix} 1 & 1 \\\\ 1 & -1 \\end{pmatrix}$.",
      "category": "generation"
    },
    {
      "instruction": "Explain how the 'Kernel Trick' allows SVMs to classify non-linearly separable data.",
      "context": "Block 2: Data Management Systems - Topic 6: Support Vector Machines (SVM).",
      "response": "Support Vector Machines (SVMs) are inherently linear classifiers. However, many real-world datasets are not linearly separable. The **Kernel Trick** allows SVMs to solve this by mapping the original input data into a higher-dimensional feature space using a kernel function (like the Radial Basis Function or Polynomial Kernel). In this higher-dimensional space, the data becomes linearly separable, allowing the SVM to find an optimal hyperplane that separates the classes without explicitly computing the coordinates of the data in that high-dimensional space.",
      "category": "open_qa"
    },
    {
      "instruction": "Given the confusion matrix: TP=50, TN=40, FP=10, FN=5. Calculate the 'Precision'.",
      "context": "Block 1: Data - Topic 3: Evaluation of classifiers (Métricas de evaluación numérica).",
      "response": "Precision is defined as the ratio of true positives to the total predicted positives.\n$Precision = \\frac{TP}{TP + FP}$.\nSubstitute the values:\n$Precision = \\frac{50}{50 + 10} = \\frac{50}{60}$.\n$Precision = \\frac{5}{6} \\approx 0.833$.",
      "category": "closed_qa"
    },
    {
      "instruction": "Summarize the 'Deutsch-Jozsa Algorithm'.",
      "context": "Block 3: Quantum Computing - Topic 11: Quantum Algorithms.",
      "response": "The Deutsch-Jozsa algorithm was one of the first to demonstrate a quantum advantage. It solves a specific 'black box' problem: determining whether a given function $f: \\{0,1\\}^n \\rightarrow \\{0,1\\}$ is constant (returns the same value for all inputs) or balanced (returns 0 for half the inputs and 1 for the other half). A classical computer would need to check $2^{n-1} + 1$ inputs in the worst case, but the Deutsch-Jozsa algorithm can solve this with certainty using only a single query to the quantum oracle.",
      "category": "summarization"
    },
    {
      "instruction": "From the text, what is 'PennyLane'?",
      "context": "Block 3: Quantum Computing - Topic 12: Optimization (Implementación en PennyLane).",
      "response": "{\n  \"definition\": \"PennyLane is a cross-platform Python library for differentiable quantum programming. It enables the optimization of quantum circuits and variational algorithms (like VQE or QAOA) by integrating with classical machine learning libraries such as PyTorch and TensorFlow.\"\n}",
      "category": "information_extraction"
    },
    {
      "instruction": "Classify the following as types of 'Noise' in data or 'Noise' in quantum computing: Outliers, Decoherence, Missing Values, Gate Errors.",
      "context": "Block 1 & Block 3.",
      "response": "{\n  \"Data Noise (Block 1)\": [\n    \"Outliers\",\n    \"Missing Values\"\n  ],\n  \"Quantum Noise (Block 3)\": [\n    \"Decoherence\",\n    \"Gate Errors\"\n  ]\n}",
      "category": "classification"
    },
    {
      "instruction": "Brainstorm steps to preprocess a dataset before feeding it into a Machine Learning model.",
      "context": "Block 1: Data - Topic 1: Treatment of data.",
      "response": "1. **Data Cleaning:** Handle missing values (imputation or removal) and remove duplicates.\n2. **Outlier Detection:** Identify and handle anomalous data points.\n3. **Feature Scaling:** Normalize (Min-Max) or Standardize (Z-score) numerical features to bring them to a common scale.\n4. **Encoding:** Convert categorical variables into numerical format (One-Hot Encoding, Label Encoding).\n5. **Feature Selection/Extraction:** Use PCA or correlation matrices to reduce dimensionality and select relevant features.\n6. **Splitting:** Divide the data into training, validation, and test sets.",
      "category": "brainstorming"
    },
    {
      "instruction": "Write a short creative poem about Gradient Descent.",
      "context": "Block 2: Data Management Systems - Topic 5: Backpropagation.",
      "response": "Upon the hill of Error high,\nWhere loss is steep and costs are nigh,\nI take a step, the gradient's guide,\nTo where the local minima hide.\n\nLearning rate, my stride so small,\nLest I overshoot and tumble, fall.\nDown the slope of weights I slide,\nUntil the global truth I bide.",
      "category": "creative_writing"
    },
    {
      "instruction": "Generate the formula for the 'Euclidean Distance' between two points $p$ and $q$ in $n$-dimensional space.",
      "context": "Block 2: Data Management Systems - Topic 7: Clustering (Distance metrics).",
      "response": "The Euclidean distance $d(p, q)$ is given by:\n$d(p, q) = \\sqrt{\\sum_{i=1}^{n} (q_i - p_i)^2}$.",
      "category": "generation"
    },

    {
      "instruction": "Explain the concept of 'Parity' ($P$) in quantum mechanics and its relevance to nuclear physics.",
      "context": "Block 1: Foundations - Topic 2: Potentials, parity, statistics and transitions.",
      "response": "Parity is a spatial inversion symmetry operation where the coordinates are transformed as $\\vec{r} \\to -\\vec{r}$. If a wave function satisfies $\\psi(-\\vec{r}) = +\\psi(\\vec{r})$, it has even parity ($+$), and if $\\psi(-\\vec{r}) = -\\psi(\\vec{r})$, it has odd parity ($-$). In nuclear physics, the strong and electromagnetic interactions conserve parity, meaning the parity of the initial state must equal the parity of the final state. However, the weak interaction (responsible for beta decay) violates parity conservation, as discovered in the famous Wu experiment.",
      "category": "open_qa"
    },
    {
      "instruction": "Calculate the energy eigenvalues for a particle of mass $m$ in a one-dimensional infinite potential well of width $L$.",
      "context": "Block 1: Foundations - Topic 2: Problems in one dimension.",
      "response": "The Schrödinger equation inside the well is $-\\frac{\\hbar^2}{2m} \\frac{d^2\\psi}{dx^2} = E\\psi$. The boundary conditions are $\\psi(0) = \\psi(L) = 0$.\nThe general solution is $\\psi(x) = A \\sin(kx) + B \\cos(kx)$.\nApplying $\\psi(0)=0$ gives $B=0$. Applying $\\psi(L)=0$ gives $kL = n\\pi$ for $n=1, 2, 3, \\dots$.\nSince $E = \\frac{\\hbar^2 k^2}{2m}$, substituting $k = \\frac{n\\pi}{L}$ yields the energy levels:\n$E_n = \\frac{n^2 \\pi^2 \\hbar^2}{2mL^2}$.",
      "category": "closed_qa"
    },
    {
      "instruction": "Summarize the role of 'Accelerators' and 'Detectors' in understanding the microscopic world.",
      "context": "Block 1: Foundations - Topic 1: Introduction.",
      "response": "Accelerators and detectors are the microscope of particle physics. Accelerators (like the LHC) boost charged particles to high kinetic energies using electromagnetic fields, allowing them to probe small scales (high momentum corresponds to short wavelength $\\lambda = h/p$) or create new massive particles via $E=mc^2$. Detectors (like ATLAS or CMS) act as cameras that record the aftermath of collisions, measuring the momentum, energy, and charge of the resulting particles to reconstruct the underlying physical events.",
      "category": "summarization"
    },
    {
      "instruction": "From the text, what constitutes 'Exotic Matter'?",
      "context": "Block 1: Foundations - Topic 1: Introduction.",
      "response": "{\n  \"definition\": \"Exotic matter refers to forms of matter that deviate from standard baryonic matter (protons and neutrons) and electrons. This includes antimatter, dark matter, quark-gluon plasma, or particles with exotic quantum numbers that do not fit the standard quark model patterns.\"\n}",
      "category": "information_extraction"
    },
    {
      "instruction": "Classify the following particles as Bosons or Fermions: Electron, Photon, Proton, Alpha particle.",
      "context": "Block 1: Foundations - Topic 2: Quantum statistics.",
      "response": "{\n  \"Fermions (Half-integer spin, obey Fermi-Dirac statistics)\": [\n    \"Electron (spin 1/2)\",\n    \"Proton (spin 1/2)\"\n  ],\n  \"Bosons (Integer spin, obey Bose-Einstein statistics)\": [\n    \"Photon (spin 1)\",\n    \"Alpha particle (nucleus of Helium-4, total spin 0)\"\n  ]\n}",
      "category": "classification"
    },
    {
      "instruction": "Brainstorm potential future discoveries that could arise from studying 'Materia Exótica' (Exotic Matter).",
      "context": "Block 1: Foundations - Topic 1: Questions for the future.",
      "response": "1.  **Direct Detection of Dark Matter:** Identifying the WIMP or axion could resolve the missing mass problem of the universe.\n2.  **Stable Superheavy Elements:** Discovering the 'Island of Stability' in the chart of nuclides.\n3.  **Supersymmetry (SUSY):** Finding superpartners to known particles, solving the hierarchy problem.\n4.  **Strange Matter:** Confirming the existence of stable strangelets.\n5.  **Tetraquarks and Pentaquarks:** Understanding complex QCD binding mechanisms beyond 3-quark baryons and 2-quark mesons.",
      "category": "brainstorming"
    },
    {
      "instruction": "Write a short creative monologue from the perspective of a particle inside a cyclotron.",
      "context": "Block 1: Foundations - Topic 1: Accelerators.",
      "response": "I am a proton, and I am dizzy. Round and round I go, spiraling outward. Every time I cross the gap between the Dees, an electric kick slaps me from behind, faster, harder. The magnetic field is a heavy hand pressing down on me, forcing me to turn, to curve, to stay within the machine. I feel heavier now—Relativity is claiming its debt. The world outside is a blur of static. I am becoming a projectile of pure kinetic rage, waiting for the final extraction, waiting to smash into the target and spill my quarks for the giants watching on the screens.",
      "category": "creative_writing"
    },
    {
      "instruction": "Generate the commutation relations for orbital angular momentum components.",
      "context": "Block 1: Foundations - Topic 2: Quantum theory of angular momentum.",
      "response": "The fundamental commutation relations for the components of the orbital angular momentum operator $\\hat{L}$ are:\n$[\\hat{L}_x, \\hat{L}_y] = i\\hbar \\hat{L}_z$\n$[\\hat{L}_y, \\hat{L}_z] = i\\hbar \\hat{L}_x$\n$[\\hat{L}_z, \\hat{L}_x] = i\\hbar \\hat{L}_y$\nIn compact notation using the Levi-Civita symbol: $[\\hat{L}_i, \\hat{L}_j] = i\\hbar \\epsilon_{ijk} \\hat{L}_k$.",
      "category": "generation"
    },
    {
      "instruction": "Explain the significance of the Semi-Empirical Mass Formula (SEMF) or Weizsäcker formula.",
      "context": "Block 2: Nuclear Physics - Topic 3: Semi-empirical mass formula.",
      "response": "The Semi-Empirical Mass Formula (SEMF) models the nucleus as a drop of incompressible liquid. It approximates the binding energy $B(A, Z)$ of a nucleus based on macroscopic and quantum mechanical effects. It includes terms for Volume (proportional to $A$), Surface (reducing binding due to surface nucleons), Coulomb (repulsion between protons), Asymmetry (penalty for $N \\neq Z$), and Pairing (favoring coupled spin pairs). It successfully explains the general trend of binding energy per nucleon and predicts nuclear stability.",
      "category": "open_qa"
    },
    {
      "instruction": "Calculate the Q-value for the alpha decay of a nucleus $^A_Z X \\to ^{A-4}_{Z-2} Y + \\alpha$.",
      "context": "Block 2: Nuclear Physics - Topic 5: Alpha decay.",
      "response": "The Q-value represents the energy released in the decay and is determined by the mass difference between the parent and the products.\n$Q = [M(^A_Z X) - M(^{A-4}_{Z-2} Y) - M(^4_2 \\text{He})]c^2$\nIf $Q > 0$, the decay is energetically allowed (exothermic). The energy is shared as kinetic energy between the alpha particle and the recoil nucleus $Y$.",
      "category": "closed_qa"
    },
    {
      "instruction": "Summarize the 'Deuteron problem' and what it tells us about nuclear forces.",
      "context": "Block 2: Nuclear Physics - Topic 4: The Deuteron.",
      "response": "The Deuteron ($^2$H) is the simplest bound nuclear system, consisting of one proton and one neutron. Studying it reveals that the nuclear force is short-range, attractive, and spin-dependent (the deuteron exists in a triplet spin state $S=1$, but not singlet). Its binding energy is very low (2.22 MeV), and it has no excited states. The non-zero quadrupole moment indicates the nuclear force has a non-central (tensor) component, meaning the nucleus is not perfectly spherical.",
      "category": "summarization"
    },
    {
      "instruction": "From the text, what are the selection rules for 'Fermi' and 'Gamow-Teller' transitions in beta decay?",
      "context": "Block 2: Nuclear Physics - Topic 5: Fermi theory of beta decay.",
      "response": "{\n  \"Fermi transitions\": \"The lepton pair (electron + neutrino) carries zero total spin ($S=0$). Selection rules: $\\Delta J = 0$ and no parity change ($\\Delta \\pi = 0$).\",\n  \"Gamow-Teller transitions\": \"The lepton pair carries a total spin of 1 ($S=1$). Selection rules: $\\Delta J = 0, \\pm 1$ (but $0 \\to 0$ is forbidden) and no parity change ($\\Delta \\pi = 0$).\"\n}",
      "category": "information_extraction"
    },
    {
      "instruction": "Classify the following decays based on the force responsible: Alpha decay, Beta decay, Gamma decay.",
      "context": "Block 2: Nuclear Physics - Topic 5: Types of radioactivity.",
      "response": "{\n  \"Strong Interaction / Tunneling (Coulomb)\": \"Alpha decay (emission of Helium nucleus via tunneling through Coulomb barrier).\",\n  \"Weak Interaction\": \"Beta decay (transformation of neutron to proton or vice-versa involving W bosons).\",\n  \"Electromagnetic Interaction\": \"Gamma decay (emission of high energy photon from excited nuclear state).\"\n}",
      "category": "classification"
    },
    {
      "instruction": "Brainstorm applications of nuclear fission beyond electricity generation.",
      "context": "Block 2: Nuclear Physics - Topic 5: Fission/Applications.",
      "response": "1.  **Radioisotope Production:** Creating isotopes like Mo-99 for medical imaging (Technetium-99m).\n2.  **Nuclear Propulsion:** Thermal rockets for deep space exploration.\n3.  **Neutron Sources:** For materials science research (neutron diffraction).\n4.  **Transmutation:** Converting long-lived nuclear waste into shorter-lived isotopes.\n5.  **Defense:** Obviously, nuclear weaponry.",
      "category": "brainstorming"
    },
    {
      "instruction": "Write a short creative story about a neutron deciding to undergo beta decay.",
      "context": "Block 2: Nuclear Physics - Topic 5: Beta decay.",
      "response": "I am a Neutron, sitting alone in free space. I feel... heavy. Uneasy. My internal quarks are restless. One of my Down quarks is whispering that it wants to change. 'Be Up,' it says. 'Be positive.' The Weak Force urges me on, offering a transactional boson, a $W^-$. I can't hold it anymore. With a sudden snap of probability, I transform. I am no longer neutral. I am a Proton now. But I had to pay the price. I threw out a fast-moving electron to balance the charge and a tiny, ghostly anti-neutrino to save the energy. I feel lighter, stable, and positively charged.",
      "category": "creative_writing"
    },
    {
      "instruction": "Generate the formula for the radioactive decay law involving half-life.",
      "context": "Block 2: Nuclear Physics - Topic 5: Radioactivity.",
      "response": "The number of radioactive nuclei $N(t)$ remaining at time $t$ is given by:\n$N(t) = N_0 e^{-\\lambda t}$\nwhere $N_0$ is the initial number of nuclei and $\\lambda$ is the decay constant. Expressed in terms of half-life $T_{1/2}$:\n$N(t) = N_0 \\left(\\frac{1}{2}\\right)^{t / T_{1/2}}$.",
      "category": "generation"
    },
    {
      "instruction": "Explain the concept of 'Color Confinement' in Quantum Chromodynamics (QCD).",
      "context": "Block 3: Particle Physics - Topic 7: QCD.",
      "response": "Color confinement is the phenomenon that color-charged particles (quarks and gluons) cannot be isolated, and therefore cannot be directly observed in normal conditions below the Hagedorn temperature. Quarks are clumped together to form color-neutral hadrons (like protons and neutrons). If you try to separate two quarks, the energy in the gluon field between them increases linearly with distance ($V(r) \\sim kr$) until it is energetically favorable to create a new quark-antiquark pair from the vacuum, snapping the 'string' rather than isolating the quark.",
      "category": "open_qa"
    },
    {
      "instruction": "Calculate the threshold energy for the reaction $p + p \\to p + p + p + \\bar{p}$ in a fixed target experiment.",
      "context": "Block 3: Particle Physics - Topic 8: Relativistic kinematics.",
      "response": "The threshold kinetic energy $T_{th}$ for a particle of mass $m$ hitting a stationary target of mass $m$ to produce a final state of total mass $M$ is given by:\n$T_{th} = \\frac{(M c^2)^2 - (2m c^2)^2}{2m c^2}$.\nHere, $m = m_p$ and the final state is $4m_p$ ($M=4m_p$).\n$T_{th} = \\frac{(4m_p c^2)^2 - (2m_p c^2)^2}{2m_p c^2} = \\frac{16m_p^2 c^4 - 4m_p^2 c^4}{2m_p c^2}$\n$T_{th} = \\frac{12m_p^2 c^4}{2m_p c^2} = 6m_p c^2$.\nThe protons must have a kinetic energy of $6 \\times 938$ MeV.",
      "category": "closed_qa"
    },
    {
      "instruction": "Summarize the 'Standard Model' of particle physics.",
      "context": "Block 3: Particle Physics - Topic 6: The Standard Model.",
      "response": "The Standard Model is a theoretical framework that describes three of the four known fundamental forces (electromagnetic, weak, and strong interactions, excluding gravity) and classifies all known elementary particles. It consists of Fermions (matter particles: 6 quarks and 6 leptons organized in three generations) and Bosons (force carriers: photon, $W^{\\pm}$, $Z^0$, gluons). It also includes the Higgs boson, which gives mass to particles via the Higgs mechanism.",
      "category": "summarization"
    },
    {
      "instruction": "From the text, what are the 'Four Fundamental Forces'?",
      "context": "Block 3: Particle Physics - Topic 7: Interactions.",
      "response": "{\n  \"Gravity\": \"Acts on mass/energy, infinite range, weakest force (not fully integrated in Standard Model).\",\n  \"Electromagnetism\": \"Acts on electric charge, infinite range, mediated by photons.\",\n  \"Weak Nuclear Force\": \"Acts on flavor, short range, mediated by W and Z bosons, responsible for decay.\",\n  \"Strong Nuclear Force\": \"Acts on color charge, short range, mediated by gluons, binds quarks and nuclei.\"\n}",
      "category": "information_extraction"
    },
    {
      "instruction": "Classify the following hadrons as Baryons or Mesons: Proton, Pion, Neutron, Kaon.",
      "context": "Block 3: Particle Physics - Topic 6: Proliferation of hadrons.",
      "response": "{\n  \"Baryons (3 quarks, fermions)\": [\n    \"Proton ($uud$)\",\n    \"Neutron ($udd$)\"\n  ],\n  \"Mesons (Quark-antiquark pair, bosons)\": [\n    \"Pion (e.g., $\\pi^+ = u\\bar{d}$)\",\n    \"Kaon (e.g., $K^+ = u\\bar{s}$)\"\n  ]\n}",
      "category": "classification"
    },
    {
      "instruction": "Brainstorm why the neutrino was so difficult to discover.",
      "context": "Block 3: Particle Physics - Topic 6: The neutrino.",
      "response": "1.  **No Charge:** It has zero electric charge, so it doesn't interact electromagnetically (no ionization tracks).2.  **Weak Interaction Only:** It only interacts via the weak force (and gravity), meaning the cross-section for interaction is infinitesimally small.\n3.  **Low Mass:** Initially thought to be massless, its mass is so small it creates almost no gravitational disturbance.\n4.  **Penetration:** A neutrino can pass through a light-year of lead without stopping.\n5.  **Background Noise:** Detecting them requires deep underground labs to shield from cosmic rays.",
      "category": "brainstorming"
    },
    {
      "instruction": "Write a short creative dialogue between a Quark and an Antiquark.",
      "context": "Block 3: Particle Physics - Topic 6: Antimatter.",
      "response": "Up Quark: \"You look just like me, but everything is... backwards.\"\nAnti-Up Quark: \"I am your mirror image. Your charge is $+2/3$; mine is $-2/3$. You are matter; I am the void's answer.\"\nUp Quark: \"If we touch, we vanish.\"\nAnti-Up Quark: \"Not vanish. We become light. We become pure energy. A gluon, a photon. We return to the field.\"\nUp Quark: \"Then let us dance, and light up the detector.\"",
      "category": "creative_writing"
    },
    {
      "instruction": "Generate the definition of a relativistic 4-vector.",
      "context": "Block 3: Particle Physics - Topic 8: Cuadrivectores.",
      "response": "A 4-vector $A^\\mu$ is a collection of four components $(A^0, A^1, A^2, A^3)$ that transforms under a Lorentz transformation $\\Lambda^{\\mu}_{\\nu}$ as:\n$A'^\\mu = \\Lambda^{\\mu}_{\\nu} A^\\nu$\nA common example is the position 4-vector $x^\\mu = (ct, x, y, z)$ and the energy-momentum 4-vector $p^\\mu = (E/c, p_x, p_y, p_z)$.",
      "category": "generation"
    },
    {
      "instruction": "Explain the physical meaning of the 'Dirac Equation' compared to the Schrödinger equation.",
      "context": "Block 4: Intro to QFT - Topic 10: The Dirac equation.",
      "response": "The Schrödinger equation is non-relativistic and describes spinless particles (or treats spin ad-hoc). The Dirac equation, $i\\hbar\\gamma^\\mu\\partial_\\mu\\psi - mc\\psi = 0$, is a fully relativistic wave equation. It naturally accounts for spin-1/2 particles (fermions like electrons) by using 4-component spinors instead of scalar wavefunctions. Crucially, it predicted the existence of antimatter (positrons) as a necessary consequence of combining quantum mechanics with special relativity.",
      "category": "open_qa"
    },
    {
      "instruction": "Show that the product of Gamma matrices $\\gamma^\\mu \\gamma^\\nu + \\gamma^\\nu \\gamma^\\mu$ equals the metric tensor.",
      "context": "Block 4: Intro to QFT - Topic 10: Dirac equation matrices.",
      "response": "The Dirac gamma matrices $\\gamma^\\mu$ are defined by the Clifford algebra anticommutation relation:\n$\\{ \\gamma^\\mu, \\gamma^\\nu \\} = \\gamma^\\mu \\gamma^\\nu + \\gamma^\\nu \\gamma^\\mu = 2\\eta^{\\mu\\nu} I$\nwhere $\\eta^{\\mu\\nu}$ is the Minkowski metric tensor (usually diag(+1, -1, -1, -1)) and $I$ is the $4 \\times 4$ identity matrix.",
      "category": "closed_qa"
    },
    {
      "instruction": "Summarize the concept of 'Gauge Invariance' in field theory.",
      "context": "Block 4: Intro to QFT - Topic 10: Invariancia gauge local.",
      "response": "Gauge invariance is a symmetry principle stating that the Lagrangian of a physical system remains unchanged (invariant) under certain local transformations of the fields. For example, in QED, changing the phase of the electron field locally, $\\psi(x) \\to e^{i\\alpha(x)}\\psi(x)$, requires the introduction of a gauge field (the photon field $A_\\mu$) to maintain invariance. This principle dictates the form of the interactions between matter and forces.",
      "category": "summarization"
    },
    {
      "instruction": "From the text, what is the 'Lagrangian Density' for a free scalar field?",
      "context": "Block 4: Intro to QFT - Topic 10: Lagrangianos.",
      "response": "{\n  \"Lagrangian Density (Klein-Gordon)\": \"$\\mathcal{L} = \\frac{1}{2} (\\partial_\\mu \\phi)(\\partial^\\mu \\phi) - \\frac{1}{2} m^2 \\phi^2$\"\n}",
      "category": "information_extraction"
    },
    {
      "instruction": "Classify the following mathematical objects in the Dirac theory: $\\bar{\\psi}\\psi$, $\\bar{\\psi}\\gamma^5\\psi$, $\\bar{\\psi}\\gamma^\\mu\\psi$.",
      "context": "Block 4: Intro to QFT - Topic 10: Bilineales.",
      "response": "{\n  \"Scalar\": \"$\\bar{\\psi}\\psi$ (invariant under Lorentz transformations).\",\n  \"Pseudo-scalar\": \"$\\bar{\\psi}\\gamma^5\\psi$ (behaves like a scalar but flips sign under parity).\",\n  \"Vector\": \"$\\bar{\\psi}\\gamma^\\mu\\psi$ (transforms like a 4-vector, represents the current).\"\n}",
      "category": "classification"
    },
    {
      "instruction": "Brainstorm analogies for a 'Quantum Field'.",
      "context": "Block 4: Intro to QFT - Topic 10: Introduction.",
      "response": "1.  **The Mattress:** The field is an infinite mattress. A particle is a localized vibration or 'bounce' on that mattress.\n2.  **The Ocean:** The field is the ocean water covering everything. Particles are the waves traveling on the surface.\n3.  **Guitar String:** The field is the string itself, extending everywhere. A particle is a specific note or harmonic plucked on that string.\n4.  **Fluid:** The field is a fluid filling space; excitations in the fluid (vortices or waves) are what we perceive as particles.",
      "category": "brainstorming"
    },
    {
      "instruction": "Write a short creative explanation of why we need 'Bilinears' in Dirac theory.",
      "context": "Block 4: Intro to QFT - Topic 10: Bilineals.",
      "response": "Imagine the wavefunction $\\psi$ is a ghost—it has complex components and isn't a real observable quantity. To make something real, something we can measure like energy or current, we need to ground it. We can't just square it like a number. We need its conjugate partner, $\\bar{\\psi}$ (psi-bar). When $\\psi$ and $\\bar{\\psi}$ hold hands (sandwiching a gamma matrix matrix in between), the imaginary ghosts vanish, and a real, physical observable emerges from the mist. These pairings, these bilinears, are the building blocks of reality.",
      "category": "creative_writing"
    },
    {
      "instruction": "Generate the Dirac equation in covariant form.",
      "context": "Block 4: Intro to QFT - Topic 10: Dirac equation.",
      "response": "The Dirac equation for a fermion of mass $m$ is:\n$(i \\gamma^\\mu \\partial_\\mu - m) \\psi = 0$\nwhere $\\psi$ is the spinor field, $\\gamma^\\mu$ are the gamma matrices, and $\\partial_\\mu$ is the 4-gradient.",
      "category": "generation"
    },


#Physics

  # --- CATEGORY: OPEN_QA ---
  {
    "instruction": "Explain the concept of 'Bras' and 'Kets' in Dirac notation.",
    "context": "Topic 1: Formalismo de Dirac.",
    "response": "In Dirac notation, the state of a quantum system is represented by a vector in a complex Hilbert space, denoted as a 'Ket' $|\\psi\\rangle$. The dual space consists of linear functionals that map these Kets to complex numbers; these are denoted as 'Bras' $\\langle\\psi|$. The inner product of a Bra and a Ket, written as $\\langle\\phi|\\psi\\rangle$, is a complex scalar representing the probability amplitude of finding state $|\\psi\\rangle$ in state $|\\phi\\rangle$.",
    "category": "open_qa"
  },
  {
    "instruction": "What is the physical significance of the commutator of two observables?",
    "context": "Topic 2: Commutators and anticonmutators.",
    "response": "The commutator of two observables $\\hat{A}$ and $\\hat{B}$, defined as $[\\hat{A}, \\hat{B}] = \\hat{A}\\hat{B} - \\hat{B}\\hat{A}$, determines whether they can be simultaneously measured with arbitrary precision. If the commutator is zero ($[\\hat{A}, \\hat{B}] = 0$), the observables are compatible and share a common set of eigenstates. If it is non-zero, they are incompatible and obey an uncertainty relation (like position and momentum).",
    "category": "open_qa"
  },
  {
    "instruction": "How is the momentum operator defined as a generator of translation?",
    "context": "Topic 3: Momentum as a generator of translations.",
    "response": "The momentum operator $\\hat{p}$ is defined as the generator of spatial translations. The translation operator $\\hat{T}(dx)$ for an infinitesimal displacement $dx$ is given by $\\hat{T}(dx) = 1 - \\frac{i}{\\hbar}\\hat{p} dx$. This definition implies that applying momentum to a state is equivalent to examining how the state changes under a small shift in position.",
    "category": "open_qa"
  },

  # --- CATEGORY: CLOSED_QA ---
  {
    "instruction": "If $|\\psi\\rangle$ is a normalized state, what is the value of $\\langle\\psi|\\psi\\rangle$?",
    "context": "Topic 1: The Bra space and inner product.",
    "response": "1",
    "category": "closed_qa"
  },
  {
    "instruction": "Write the projection operator $\\hat{P}_n$ for a discrete orthonormal basis state $|n\\rangle$.",
    "context": "Topic 1: Operators.",
    "response": "$\\hat{P}_n = |n\\rangle\\langle n|$",
    "category": "closed_qa"
  },
  {
    "instruction": "In the position representation, what is the mathematical form of the momentum operator $\\hat{p}$?",
    "context": "Topic 3: The momentum operator in position space.",
    "response": "$\\hat{p} = -i\\hbar \\frac{\\partial}{\\partial x}$",
    "category": "closed_qa"
  },

  # --- CATEGORY: SUMMARIZATION ---
  {
    "instruction": "Summarize the properties of Hermitian operators.",
    "context": "Topic 1: Operators.",
    "response": "Hermitian operators are linear operators that are equal to their own adjoint (conjugate transpose), i.e., $\\hat{A} = \\hat{A}^\\dagger$. They have two crucial properties in quantum mechanics: 1) Their eigenvalues are always real numbers, making them suitable for representing physical observables. 2) The eigenstates corresponding to different eigenvalues are orthogonal, forming a complete basis for the Hilbert space.",
    "category": "summarization"
  },
  {
    "instruction": "Summarize the concept of 'Change of Basis' in quantum mechanics.",
    "context": "Topic 2: Transformation operator.",
    "response": "A change of basis involves expressing a quantum state or operator, currently defined in one basis (e.g., position), in terms of another basis (e.g., momentum). This is achieved using a unitary transformation operator $\\hat{U}$. The matrix elements of $\\hat{U}$ connect the basis vectors of the old and new representations. Physically, this does not change the state itself, only its mathematical description.",
    "category": "summarization"
  },

  # --- CATEGORY: INFORMATION_EXTRACTION ---
  {
    "instruction": "Extract the completeness relation (resolution of identity) for a discrete basis $\{|a_n\\rangle\}$.",
    "context": "Topic 1: Formalism of Dirac.",
    "response": "{\n  \"relation\": \"$\\sum_n |a_n\\rangle\\langle a_n| = \\hat{I}$\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Identify the condition for two observables to be compatible.",
    "context": "Topic 2.",
    "response": "{\n  \"condition\": \"Their commutator is zero: $[\\hat{A}, \\hat{B}] = 0$.\"\n}",
    "category": "information_extraction"
  },

  # --- CATEGORY: CLASSIFICATION ---
  {
    "instruction": "Classify the following spectra: Position operator, Harmonic Oscillator Hamiltonian.",
    "context": "Topic 3: Continuous spectra.",
    "response": "{\n  \"Continuous Spectrum\": \"Position operator ($\\hat{x}$)\",\n  \"Discrete Spectrum\": \"Harmonic Oscillator Hamiltonian\"\n}",
    "category": "classification"
  },
  {
    "instruction": "Classify the operator $\\hat{U}(\\theta) = e^{-i\\hat{A}\\theta}$ based on whether $\\hat{A}$ is Hermitian.",
    "context": "Topic 1/2.",
    "response": "{\n  \"If A is Hermitian\": \"$\\hat{U}$ is Unitary (preserves norm).\",\n  \"If A is anti-Hermitian\": \"$\\hat{U}$ is not Unitary (norm changes).\"\n}",
    "category": "classification"
  },

  # --- CATEGORY: BRAINSTORMING ---
  {
    "instruction": "Brainstorm analogies for the collapse of the wavefunction upon measurement.",
    "context": "Topic 2: Measurements.",
    "response": "-   **The Dice Roll:** The state is the spinning die (probability cloud); measurement is the die stopping on a number.\n-   **The Coin Spin:** A coin spinning is both heads and tails; slapping it onto the table forces a choice.\n-   **The Jury:** A jury's opinion is a superposition of 'guilty' and 'not guilty' until the foreman reads the verdict.\n-   **The Pixelated Screen:** An image loading that is blurry (superposition) suddenly snapping into high-definition focus.",
    "category": "brainstorming"
  },

  # --- CATEGORY: CREATIVE_WRITING ---
  {
    "instruction": "Write a short dialogue between a Bra and a Ket trying to meet.",
    "context": "Topic 1: Dirac Formalism.",
    "response": "Ket: \"I am a column of infinite possibilities, standing tall in the vector space!\"\nBra: \"And I am your row, your destiny, lying in wait in the dual space.\"\nKet: \"We are from different worlds. I am complex, you are conjugate.\"\nBra: \"But if we meet... if we effectuate the inner product...\"\nKet: \"We become one. A scalar. A pure probability amplitude.\"\nBra: \"Then let's close the bracket. $\\langle \\text{us} | \\text{us} \\rangle = 1$.\"",
    "category": "creative_writing"
  },

  # --- CATEGORY: GENERATION ---
  {
    "instruction": "Generate the matrix element notation for an operator $\\hat{A}$ in basis $\{|n\\rangle\}$.",
    "context": "Topic 1: Matrix representation.",
    "response": "$A_{nm} = \\langle n | \\hat{A} | m \\rangle$",
    "category": "generation"
  },
  {
    "instruction": "Generate the translation operator formula for a finite displacement $a$.",
    "context": "Topic 3: Translation.",
    "response": "$\\hat{T}(a) = e^{-i\\hat{p}a/\\hbar}$",
    "category": "generation"
  },

  # =================================================================================================
  # BLOQUE 2: SCHRÖDINGER VERSUS HEISENBERG (Topics 4, 5, 6)
  # Covers: Time Evolution, Pictures, Ehrenfest Theorem, Harmonic Oscillator
  # =================================================================================================

  # --- CATEGORY: OPEN_QA ---
  {
    "instruction": "What is the fundamental difference between the Schrödinger Picture and the Heisenberg Picture?",
    "context": "Topic 5: Images of Schrödinger and Heisenberg.",
    "response": "In the **Schrödinger Picture**, the state vectors (kets) evolve in time according to the Schrödinger equation, while operators (observables) are generally constant in time. In the **Heisenberg Picture**, the situation is reversed: state vectors are frozen in time (at $t=0$), while the operators evolve in time according to the Heisenberg equation of motion. Both pictures yield identical predictions for physical measurements (expectation values).",
    "category": "open_qa"
  },
  {
    "instruction": "Explain the significance of the Ehrenfest Theorem.",
    "context": "Topic 5: The free particle and Ehrenfest theorem.",
    "response": "The Ehrenfest Theorem relates the time evolution of quantum expectation values to classical equations of motion. It states that the expectation values of position and momentum obey Newton's laws (e.g., $\\frac{d}{dt}\\langle p \\rangle = \\langle -\\nabla V \\rangle$). This theorem provides a crucial link between quantum mechanics and classical mechanics, showing how classical behavior emerges as an average of quantum behavior.",
    "category": "open_qa"
  },
  {
    "instruction": "How is the Time Evolution Operator $\\hat{U}(t, t_0)$ related to the Hamiltonian?",
    "context": "Topic 4: The time evolution operator.",
    "response": "The Hamiltonian $\\hat{H}$ is the generator of time evolution. If the Hamiltonian is time-independent, the time evolution operator is given by $\\hat{U}(t, t_0) = e^{-i\\hat{H}(t-t_0)/\\hbar}$. This operator is unitary and propagates a quantum state from time $t_0$ to time $t$ via $|\\psi(t)\\rangle = \\hat{U}(t, t_0)|\\psi(t_0)\\rangle$.",
    "category": "open_qa"
  },

  # --- CATEGORY: CLOSED_QA ---
  {
    "instruction": "Write the Heisenberg equation of motion for an operator $\\hat{A}_H(t)$.",
    "context": "Topic 5.",
    "response": "$\\frac{d\\hat{A}_H}{dt} = \\frac{i}{\\hbar} [\\hat{H}, \\hat{A}_H] + \\left(\\frac{\\partial \\hat{A}}{\\partial t}\\right)_H$",
    "category": "closed_qa"
  },
  {
    "instruction": "For a time-independent Hamiltonian, what is the time dependence of an energy eigenstate $|E_n\\rangle$?",
    "context": "Topic 4: Energy eigenkets.",
    "response": "$|E_n(t)\\rangle = e^{-iE_n t/\\hbar} |E_n(0)\\rangle$",
    "category": "closed_qa"
  },
  {
    "instruction": "What is the value of the commutator $[x, p]$?",
    "context": "Canonical commutation relation.",
    "response": "$i\\hbar$",
    "category": "closed_qa"
  },

  # --- CATEGORY: SUMMARIZATION ---
  {
    "instruction": "Summarize the energy-time uncertainty relation.",
    "context": "Topic 4.",
    "response": "The energy-time uncertainty relation, $\\Delta E \\Delta t \\ge \\hbar/2$, is distinct from the position-momentum relation because time is a parameter, not an operator. It implies that a state with a very precise energy (small $\\Delta E$) must last for a long time (large $\\Delta t$). Conversely, unstable states with short lifetimes (small $\\Delta t$) have significant uncertainty in their energy (large natural linewidth). It also relates the time scale of evolution of a system to the energy spread of its state.",
    "category": "summarization"
  },
  {
    "instruction": "Summarize the Gauge Transformation in Quantum Mechanics.",
    "context": "Topic 6: Gauge transformations in electromagnetism.",
    "response": "In quantum mechanics, the electromagnetic potentials $\\vec{A}$ and $\\phi$ appear in the Schrödinger equation. A gauge transformation changes these potentials ($\vec{A} \\to \\vec{A} + \\nabla \\chi$, $\\phi \\to \\phi - \\partial \\chi / \\partial t$) without changing the physical fields $\\vec{E}$ and $\\vec{B}$. To ensure the physical predictions (probabilities) remain invariant, the wavefunction must simultaneously undergo a local phase transformation: $\\psi \\to e^{iq\\chi/\\hbar}\\psi$. This invariance under local phase transformations is the basis of gauge theories.",
    "category": "summarization"
  },

  # --- CATEGORY: INFORMATION_EXTRACTION ---
  {
    "instruction": "Extract the form of the time-dependent Schrödinger equation.",
    "context": "Topic 4.",
    "response": "{\n  \"equation\": \"$i\\hbar \\frac{\\partial}{\\partial t} |\\psi(t)\\rangle = \\hat{H} |\\psi(t)\\rangle$\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Identify the generator of time translation.",
    "context": "Topic 4.",
    "response": "{\n  \"Generator\": \"The Hamiltonian Operator ($\\hat{H}$)\"\n}",
    "category": "information_extraction"
  },

  # --- CATEGORY: CLASSIFICATION ---
  {
    "instruction": "Classify the following pictures based on time-dependence of operators.",
    "context": "Topic 5.",
    "response": "{\n  \"Operators evolve in time\": \"Heisenberg Picture\",\n  \"Operators constant (usually)\": \"Schrödinger Picture\",\n  \"Operators evolve with H_0\": \"Interaction (Dirac) Picture\"\n}",
    "category": "classification"
  },
  {
    "instruction": "Classify potentials as Constant or Time-Dependent.",
    "context": "Topic 6.",
    "response": "{\n  \"Constant Potentials\": \"Step potential, Barrier potential, Finite well (Stationary states exist).\",\n  \"Time-Dependent Potentials\": \"Oscillating field, turned-on interaction (Requires perturbation theory or numerical methods).\"\n}",
    "category": "classification"
  },

  # --- CATEGORY: BRAINSTORMING ---
  {
    "instruction": "Brainstorm physical phenomena explained by the Schrödinger equation in constant potentials.",
    "context": "Topic 6.",
    "response": "-   **Quantum Tunneling:** Alpha decay, scanning tunneling microscopy (barrier potential).\n-   **Bound States:** Energy levels in atoms (Coulomb potential), quantum dots (finite well).\n-   **Reflection/Transmission:** Scattering of electrons off crystal surfaces (step potential).\n-   **Periodic Potentials:** Band structure in solids (Kronig-Penney model).",
    "category": "brainstorming"
  },

  # --- CATEGORY: CREATIVE_WRITING ---
  {
    "instruction": "Write a debate between Schrödinger and Heisenberg about whose picture is better.",
    "context": "Topic 5.",
    "response": "Schrödinger: \"My picture is intuitive! The wave function evolves like a ripple in a pond. You can visualize the probability flowing.\"\nHeisenberg: \"But Erwin, we measure observables, not wave functions. In my picture, the operators move, just like classical variables satisfy equations of motion. It is the direct link to the classical limit!\"\nSchrödinger: \"But your states are frozen statues! Where is the life?\"\nHeisenberg: \"The life is in the algebra, my friend. The matrices dance, and the commutation relations sing the song of uncertainty.\"",
    "category": "creative_writing"
  },

  # --- CATEGORY: GENERATION ---
  {
    "instruction": "Generate the Baker-Campbell-Hausdorff formula for $e^A B e^{-A}$.",
    "context": "Topic 5 (often used in deriving Heisenberg equations).",
    "response": "$e^{\\hat{A}} \\hat{B} e^{-\\hat{A}} = \\hat{B} + [\\hat{A}, \\hat{B}] + \\frac{1}{2!} [\\hat{A}, [\\hat{A}, \\hat{B}]] + \\dots$",
    "category": "generation"
  },
  {
    "instruction": "Generate the expectation value of an operator $\\hat{A}$ at time $t$ in the Heisenberg picture.",
    "context": "Topic 5.",
    "response": "$\\langle \\hat{A} \\rangle_t = \\langle \\psi(0) | \\hat{A}_H(t) | \\psi(0) \\rangle$",
    "category": "generation"
  },

  # =================================================================================================
  # BLOQUE 3: MOMENTO ANGULAR Y ESPÍN (Topic 7)
  # Covers: Angular Momentum Theory, Rotations, Spin, Pauli Formalism
  # =================================================================================================

  # --- CATEGORY: OPEN_QA ---
  {
    "instruction": "Why are half-integer values allowed for spin but not for orbital angular momentum?",
    "context": "Topic 7: Theory of angular momentum.",
    "response": "Orbital angular momentum $\\vec{L} = \\vec{r} \\times \\vec{p}$ is associated with spatial wavefunctions $\\psi(\\vec{r})$. The requirement that the wavefunction be single-valued in space (invariant under a $2\\pi$ rotation) restricts the quantum number $l$ to integers. Spin $\\vec{S}$, however, is an intrinsic property not associated with spatial coordinates. The general algebra of angular momentum $[J_i, J_j] = i\\hbar\\epsilon_{ijk}J_k$ allows for half-integer eigenvalues, which are realized physically as Spin.",
    "category": "open_qa"
  },
  {
    "instruction": "Explain the concept of Larmor Precession for a spin-1/2 particle.",
    "context": "Topic 7: Precession of spin.",
    "response": "When a particle with a magnetic moment (like an electron with spin) is placed in a uniform magnetic field $\\vec{B}$, the field exerts a torque on the magnetic moment. In quantum mechanics, this results in the time evolution of the spin expectation value. The spin vector precesses (rotates) around the direction of the magnetic field at the Larmor frequency $\\omega = \\gamma B$, where $\\gamma$ is the gyromagnetic ratio.",
    "category": "open_qa"
  },

  # --- CATEGORY: CLOSED_QA ---
  {
    "instruction": "What are the eigenvalues of the operator $\\hat{S}^2$ for an electron?",
    "context": "Spin 1/2.",
    "response": "$s(s+1)\\hbar^2 = \\frac{1}{2}(\\frac{3}{2})\\hbar^2 = \\frac{3}{4}\\hbar^2$",
    "category": "closed_qa"
  },
  {
    "instruction": "Write the Pauli matrix $\\sigma_y$.",
    "context": "Topic 7: Pauli formalism.",
    "response": "$\\sigma_y = \\begin{pmatrix} 0 & -i \\\\ i & 0 \\end{pmatrix}$",
    "category": "closed_qa"
  },
  {
    "instruction": "What is the generator of rotations around the z-axis?",
    "context": "Topic 7: Rotations.",
    "response": "The operator $\\hat{J}_z$ (Angular Momentum z-component).",
    "category": "closed_qa"
  },

  # --- CATEGORY: SUMMARIZATION ---
  {
    "instruction": "Summarize the commutation relations for angular momentum.",
    "context": "Topic 7.",
    "response": "The components of the angular momentum operator $\\vec{J}$ do not commute with each other. The fundamental relation is $[\\hat{J}_i, \\hat{J}_j] = i\\hbar \\epsilon_{ijk} \\hat{J}_k$. This implies that one cannot simultaneously know all three components of angular momentum. However, $\\hat{J}^2$ commutes with all components ($[\\hat{J}^2, \\hat{J}_i] = 0$), allowing simultaneous eigenstates of magnitude and one component (conventionally $J_z$).",
    "category": "summarization"
  },
  {
    "instruction": "Summarize the Pauli Formalism for spin-1/2.",
    "context": "Topic 7.",
    "response": "The Pauli formalism describes spin-1/2 particles using two-component spinors. Observables are represented by $2\\times2$ Hermitian matrices. The spin operators are $\\hat{S}_i = \\frac{\\hbar}{2}\\sigma_i$, where $\\sigma_i$ are the Pauli matrices. This formalism successfully captures the non-classical two-valuedness of electron spin and its interaction with magnetic fields.",
    "category": "summarization"
  },

  # --- CATEGORY: INFORMATION_EXTRACTION ---
  {
    "instruction": "Extract the rotation operator for a rotation by angle $\\phi$ about the n-axis.",
    "context": "Topic 7.",
    "response": "{\n  \"Operator\": \"$\\hat{R}_{\\hat{n}}(\\phi) = e^{-i \\vec{J} \\cdot \\hat{n} \\phi / \\hbar}$\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Identify the ladder operators for angular momentum.",
    "context": "Topic 7.",
    "response": "{\n  \"Raising\": \"$\\hat{J}_+ = \\hat{J}_x + i\\hat{J}_y$\",\n  \"Lowering\": \"$\\hat{J}_- = \\hat{J}_x - i\\hat{J}_y$\"\n}",
    "category": "information_extraction"
  },

  # --- CATEGORY: CLASSIFICATION ---
  {
    "instruction": "Classify the representations of the rotation group $SO(3)$ vs $SU(2)$.",
    "context": "Topic 7.",
    "response": "{\n  \"SO(3)\": \"Integer angular momentum (Orbital). $2\\pi$ rotation returns to same state.\",\n  \"SU(2)\": \"Half-integer angular momentum (Spin). $2\\pi$ rotation introduces a minus sign (need $4\\pi$).\"\n}",
    "category": "classification"
  },
  {
    "instruction": "Classify states based on $\\hat{S}_z$ eigenstates for spin-1/2.",
    "context": "Topic 7.",
    "response": "{\n  \"Spin Up\": \"$|+\\rangle$ or $\\begin{pmatrix} 1 \\\\ 0 \\end{pmatrix}$. Eigenvalue $+\\hbar/2$.\",\n  \"Spin Down\": \"$|-\\rangle$ or $\\begin{pmatrix} 0 \\\\ 1 \\end{pmatrix}$. Eigenvalue $-\\hbar/2$.\"\n}",
    "category": "classification"
  },

  # --- CATEGORY: BRAINSTORMING ---
  {
    "instruction": "Brainstorm physical effects that depend on Spin.",
    "context": "",
    "response": "-   **Zeeman Effect:** Splitting of spectral lines in a magnetic field.\n-   **Stern-Gerlach Experiment:** Space quantization.\n-   **Ferromagnetism:** Alignment of electron spins.\n-   **NMR/MRI:** Nuclear spin resonance.\n-   **Spin-Orbit Coupling:** Fine structure of atomic spectra.\n-   **Entanglement:** Bell's inequalities tests using spin.",
    "category": "brainstorming"
  },

  # --- CATEGORY: CREATIVE_WRITING ---
  {
    "instruction": "Describe the \"dance\" of a spinor under rotation.",
    "context": "Topic 7: Rotations of spin 1/2.",
    "response": "I am a Spinor, a strange geometric creature. Turn me around 360 degrees, and I do not return to where I started; I am inverted, negative, upside down in the Hilbert space. The world must spin twice—720 degrees—for me to truly complete my circle. I carry the memory of the twist in my phase, a secret topology that the ordinary vectors cannot understand.",
    "category": "creative_writing"
  },

  # --- CATEGORY: GENERATION ---
  {
    "instruction": "Generate the matrix for the rotation operator $R_y(\\theta)$ for spin-1/2.",
    "context": "Topic 7.",
    "response": "$e^{-i\\sigma_y \\theta / 2} = \\begin{pmatrix} \\cos(\\theta/2) & -\\sin(\\theta/2) \\\\ \\sin(\\theta/2) & \\cos(\\theta/2) \\end{pmatrix}$",
    "category": "generation"
  },
  {
    "instruction": "Generate the anticommutation relation for Pauli matrices.",
    "context": "Topic 7.",
    "response": "$\\{\\sigma_i, \\sigma_j\\} = 2\\delta_{ij}I$",
    "category": "generation"
  },

  # =================================================================================================
  # BLOQUE 4: TEORÍA DE PERTURBACIONES (Topic 8)
  # Covers: Time-dependent perturbation, Two-level systems, Sinusoidal perturbations
  # =================================================================================================

  # --- CATEGORY: OPEN_QA ---
  {
    "instruction": "What is Fermi's Golden Rule?",
    "context": "Topic 8: Time-dependent perturbation theory.",
    "response": "Fermi's Golden Rule is a formula that gives the transition rate (probability of transition per unit time) from an initial eigenstate $|i\\rangle$ to a continuum of final eigenstates $|f\\rangle$ under a constant or harmonic perturbation. It states that the rate is proportional to the square of the matrix element of the perturbation and the density of final states: $W_{i\\to f} = \\frac{2\\pi}{\\hbar} |\\langle f|\\hat{V}|i\\rangle|^2 \\rho(E_f)$.",
    "category": "open_qa"
  },
  {
    "instruction": "Explain the concept of Rabi Oscillations.",
    "context": "Topic 8: Two-level systems.",
    "response": "Rabi Oscillations describe the behavior of a two-level quantum system interacting with an oscillatory driving field (like a laser or RF field) that is resonant with the energy difference between the levels. The system cyclically absorbs and emits energy, oscillating the population probability between the ground state and the excited state at a characteristic frequency called the Rabi frequency.",
    "category": "open_qa"
  },

  # --- CATEGORY: CLOSED_QA ---
  {
    "instruction": "In a two-level system with states $|1\\rangle$ and $|2\\rangle$, what represents the interaction term in the Hamiltonian?",
    "context": "Topic 8.",
    "response": "The off-diagonal elements, e.g., $H_{12} = \\langle 1 | \\hat{H} | 2 \\rangle$.",
    "category": "closed_qa"
  },
  {
    "instruction": "For a constant perturbation turned on at $t=0$, how does the transition probability scale with time for short times?",
    "context": "Topic 8.",
    "response": "It scales as $t^2$.",
    "category": "closed_qa"
  },
  {
    "instruction": "What is the 'Dyson Series' used for?",
    "context": "Topic 8: Quantum dynamics.",
    "response": "It is a perturbative expansion of the Time Evolution Operator $\\hat{U}(t, t_0)$ in the interaction picture.",
    "category": "closed_qa"
  },

  # --- CATEGORY: SUMMARIZATION ---
  {
    "instruction": "Summarize the Interaction Picture (Dirac Picture).",
    "context": "Topic 8.",
    "response": "The Interaction Picture is a hybrid between Schrödinger and Heisenberg pictures, useful for perturbation theory. The state vectors evolve according to the interaction part of the Hamiltonian ($\\hat{V}$), while the operators evolve according to the unperturbed part ($\\hat{H}_0$). This isolates the 'slow' evolution caused by the perturbation from the 'fast' trivial evolution of the free system.",
    "category": "summarization"
  },
  {
    "instruction": "Summarize the adiabatic approximation.",
    "context": "Related to time-dependent Hamiltonians.",
    "response": "The adiabatic approximation states that if a Hamiltonian changes slowly enough (compared to the characteristic time scales of the system's transitions), a system initially in an eigenstate of the instantaneous Hamiltonian will remain in the corresponding eigenstate of the evolving Hamiltonian, picking up only a dynamic and geometric phase (Berry phase), without making transitions to other states.",
    "category": "summarization"
  },

  # --- CATEGORY: INFORMATION_EXTRACTION ---
  {
    "instruction": "Extract the condition for the validity of first-order perturbation theory.",
    "context": "Topic 8.",
    "response": "{\n  \"Condition\": \"The probability of transition must remain small ($P_{i\\to f} \\ll 1$). The perturbation strength must be weak compared to the energy separation.\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Identify the key components of a sinusoidal perturbation.",
    "context": "Topic 8.",
    "response": "{\n  \"Perturbation\": \"$\\hat{V}(t) = \\hat{V} e^{i\\omega t} + \\hat{V}^\\dagger e^{-i\\omega t}$\",\n  \"Processes\": \"Absorption (energy gain) and Stimulated Emission (energy loss).\"\n}",
    "category": "information_extraction"
  },

  # --- CATEGORY: CLASSIFICATION ---
  {
    "instruction": "Classify transitions based on the perturbation frequency $\\omega$.",
    "context": "Topic 8: Resonance.",
    "response": "{\n  \"Resonant\": \"$\\hbar\\omega \\approx E_f - E_i$ (High transition probability).\",\n  \"Detuned\": \"$\\hbar\\omega \\neq E_f - E_i$ (Low transition probability, rapid oscillation).\"\n}",
    "category": "classification"
  },
  {
    "instruction": "Classify perturbations.",
    "context": "Topic 8.",
    "response": "{\n  \"Sudden\": \"Switching time $\\tau \\ll \\hbar/\\Delta E$.\",\n  \"Adiabatic\": \"Switching time $\\tau \\gg \\hbar/\\Delta E$.\",\n  \"Periodic\": \"Sinusoidal variation.\"\n}",
    "category": "classification"
  },

  # --- CATEGORY: BRAINSTORMING ---
  {
    "instruction": "Brainstorm applications of Time-Dependent Perturbation Theory.",
    "context": "",
    "response": "-   **Lasers:** Stimulated emission rates.\n-   **Spectroscopy:** Selection rules and line intensities.\n-   **NMR:** Flipping spins with RF pulses.\n-   **Photoelectric Effect:** Calculating ionization rates.\n-   **Scattering:** Deriving the Born approximation.",
    "category": "brainstorming"
  },

  # --- CATEGORY: CREATIVE_WRITING ---
  {
    "instruction": "Write a short story about an atom exposed to a resonant laser.",
    "context": "Rabi oscillations.",
    "response": "The atom sat quietly in its ground state, $|g\\rangle$. Suddenly, the Light arrived, oscillating at exactly the frequency of its heart. The atom felt a pull, a rhythmic tug towards the excited state $|e\\rangle$. It resisted at first, but the resonance was undeniable. Slowly, probability flowed. It became a mix, a superposition, 50% here, 50% there. The Light kept pushing. Soon, the atom was fully excited! But the Light was relentless. It pushed too far, driving the atom back down towards the ground. Up and down, forever cycling in the Rabi dance.",
    "category": "creative_writing"
  },

  # --- CATEGORY: GENERATION ---
  {
    "instruction": "Generate the formula for the transition probability in a two-level system with a constant perturbation (Rabi formula, detuned).",
    "context": "Topic 8.",
    "response": "$P(t) = \\frac{|V_{12}|^2}{|V_{12}|^2 + (\\hbar\\Delta/2)^2} \\sin^2\\left(\\sqrt{|V_{12}|^2/\\hbar^2 + (\\Delta/2)^2} t\\right)$",
    "category": "generation"
  },
  {
    "instruction": "Generate the first-order expansion coefficient $c_n(t)$ in perturbation theory.",
    "context": "Topic 8.",
    "response": "$c_n(t) = -\\frac{i}{\\hbar} \\int_{0}^{t} \\langle n | \\hat{H}'(t') | i \\rangle e^{i(E_n - E_i)t'/\\hbar} dt'$",
    "category": "generation"
  },

  # =================================================================================================
  # BLOQUE 5: TEORÍA DE LA DISPERSIÓN (Topic 9)
  # Covers: Scattering Theory, Partial Waves, Born Approximation
  # =================================================================================================

  # --- CATEGORY: OPEN_QA ---
  {
    "instruction": "What is the Differential Cross Section $d\\sigma/d\\Omega$?",
    "context": "Topic 9.",
    "response": "The differential cross-section represents the probability that a particle incident on a target will be scattered into a specific solid angle element $d\\Omega$. Physically, it is the ratio of the number of particles scattered per unit time into $d\\Omega$ to the incident flux (particles per unit area per unit time). It essentially describes the effective 'target area' for scattering in a specific direction.",
    "category": "open_qa"
  },
  {
    "instruction": "Explain the Partial Wave Analysis method.",
    "context": "Topic 9: Analysis of partial waves.",
    "response": "Partial Wave Analysis is a method for solving scattering problems, particularly useful at low energies. It decomposes the incident and scattered wavefunctions into a series of spherical harmonics (eigenstates of angular momentum $l$). The effect of the scattering potential is to introduce a phase shift $\\delta_l$ for each partial wave. The total cross-section is then a sum over these phase-shifted contributions.",
    "category": "open_qa"
  },

  # --- CATEGORY: CLOSED_QA ---
  {
    "instruction": "What is the Optical Theorem?",
    "context": "Topic 9.",
    "response": "It relates the total cross-section $\\sigma_{tot}$ to the imaginary part of the forward scattering amplitude $f(0)$: $\\sigma_{tot} = \\frac{4\\pi}{k} \\text{Im}[f(0)]$.",
    "category": "closed_qa"
  },
  {
    "instruction": "Under what condition is the Born Approximation valid?",
    "context": "Topic 9.",
    "response": "High energy (fast particles) and/or weak scattering potential.",
    "category": "closed_qa"
  },
  {
    "instruction": "What is the scattering amplitude $f(\\theta, \\phi)$ defined by?",
    "context": "Asymptotic wavefunction.",
    "response": "$\\psi(r) \\to e^{ikz} + f(\\theta, \\phi) \\frac{e^{ikr}}{r}$",
    "category": "closed_qa"
  },

  # --- CATEGORY: SUMMARIZATION ---
  {
    "instruction": "Summarize the Lippmann-Schwinger equation.",
    "context": "Topic 9.",
    "response": "The Lippmann-Schwinger equation is an integral equation formulation of the scattering problem. It relates the scattered wavefunction $|\\psi\\rangle$ to the incident unperturbed state $|\\phi\\rangle$ and the potential $\\hat{V}$ via the Green's function propagator. It formally states: $|\\psi\\rangle = |\\phi\\rangle + \\hat{G}_0^+ \\hat{V} |\\psi\\rangle$. It is the starting point for deriving the Born series.",
    "category": "summarization"
  },
  {
    "instruction": "Summarize the concept of 'Hard Sphere Scattering' in the low energy limit.",
    "context": "Topic 9.",
    "response": "For a hard sphere of radius $a$, low energy scattering (long wavelength $k a \\ll 1$) is dominated by the s-wave ($l=0$). The phase shift is $\\delta_0 = -ka$. The total cross-section becomes $\\sigma = 4\\pi a^2$, which is four times the geometric cross-sectional area ($\\\\pi a^2$).",
    "category": "summarization"
  },

  # --- CATEGORY: INFORMATION_EXTRACTION ---
  {
    "instruction": "Extract the First Born Approximation formula for the scattering amplitude.",
    "context": "Topic 9.",
    "response": "{\n  \"formula\": \"$f(\\theta) \\approx -\\frac{m}{2\\pi \\hbar^2} \\int V(\\vec{r}') e^{i(\\vec{k}_i - \\vec{k}_f)\\cdot \\vec{r}'} d^3r'$\",\n  \"interpretation\": \"Fourier transform of the potential.\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Identify the phase shift $\\delta_l$.",
    "context": "Topic 9.",
    "response": "{\n  \"Description\": \"The difference in phase between the asymptotic radial function of the scattered wave ($l$-th component) and the free spherical Bessel function.\"\n}",
    "category": "information_extraction"
  },

  # --- CATEGORY: CLASSIFICATION ---
  {
    "instruction": "Classify the scattering regime based on energy.",
    "context": "Topic 9.",
    "response": "{\n  \"Low Energy ($ka \\ll 1$)\": \"Partial Wave Analysis (dominated by s-wave).\",\n  \"High Energy ($ka \\gg 1$)\": \"Born Approximation.\"\n}",
    "category": "classification"
  },
  {
    "instruction": "Classify scattering types.",
    "context": "General physics.",
    "response": "{\n  \"Elastic\": \"Internal state of particles unchanged (Energy conserved).\",\n  \"Inelastic\": \"Internal state changes (Excitation/Ionization).\"\n}",
    "category": "classification"
  },

  # --- CATEGORY: BRAINSTORMING ---
  {
    "instruction": "Brainstorm experiments analyzed using scattering theory.",
    "context": "",
    "response": "-   **Rutherford Scattering:** Discovery of the nucleus.\n-   **Electron Diffraction:** Proving wave nature of matter.\n-   **Neutron Scattering:** Probing magnetic structures in solids.\n-   **Particle Colliders (LHC):** Discovering new particles.\n-   **Medical Imaging:** Analyzing tissue interactions.",
    "category": "brainstorming"
  },

  # --- CATEGORY: CREATIVE_WRITING ---
  {
    "instruction": "Describe a wave packet hitting a target potential.",
    "context": "Topic 9.",
    "response": "I was a coherent beam, marching in step towards the center. Then I felt the Potential—a mountain in the flatland of space. I couldn't stop. I crashed against it. Parts of me passed through, shifted in phase. Parts of me scattered, fanning out in spherical ripples like a stone thrown in a pond. I am no longer a beam; I am a pattern of interference, a memory of the collision written on the detector screen.",
    "category": "creative_writing"
  },

  # --- CATEGORY: GENERATION ---
  {
    "instruction": "Generate the formula for the total cross-section in terms of phase shifts.",
    "context": "Topic 9.",
    "response": "$\\sigma_{tot} = \\frac{4\\pi}{k^2} \\sum_{l=0}^{\\infty} (2l+1) \\sin^2 \\delta_l$",
    "category": "generation"
  },
  {
    "instruction": "Generate the Green's function for the free particle (outgoing wave).",
    "context": "Topic 9.",
    "response": "$G(\\vec{r}, \\vec{r}') = -\\frac{m}{2\\pi \\hbar^2} \\frac{e^{ik|\\vec{r} - \\vec{r}'|}}{|\\vec{r} - \\vec{r}'|}$",
    "category": "generation"
  },

  # =================================================================================================
  # BLOQUE 6: ECUACIÓN DE DIRAC (Topic 10)
  # Covers: Dirac Equation, Relativistic Quantum Mechanics, Solutions
  # =================================================================================================

  # --- CATEGORY: OPEN_QA ---
  {
    "instruction": "Why did Dirac introduce his equation?",
    "context": "Topic 10: Introduction.",
    "response": "Dirac introduced his equation to resolve the problems of the Klein-Gordon equation, specifically the negative probability densities arising from the second-order time derivative. He sought a relativistic wave equation that was first-order in both time and space (like Schrödinger's), consistent with Special Relativity ($E^2 = p^2c^2 + m^2c^4$), and described spin-1/2 fermions (electrons) naturally.",
    "category": "open_qa"
  },
  {
    "instruction": "What is the physical interpretation of the 'negative energy' solutions in the Dirac equation?",
    "context": "Topic 10.",
    "response": "The Dirac equation predicts states with negative energy ($E < -mc^2$). Dirac interpreted this using the 'Hole Theory': the vacuum is a sea of completely filled negative energy states (Dirac Sea). A 'hole' in this sea (absence of a negative energy electron) behaves like a particle with positive energy and positive charge. This was the prediction of the **positron** (antimatter).",
    "category": "open_qa"
  },

  # --- CATEGORY: CLOSED_QA ---
  {
    "instruction": "How many components does a Dirac spinor have?",
    "context": "Topic 10.",
    "response": "4 components (describing particle/antiparticle and spin up/down).",
    "category": "closed_qa"
  },
  {
    "instruction": "Write the Dirac equation in covariant form.",
    "context": "Topic 10.",
    "response": "$(i\\gamma^\\mu \\partial_\\mu - m)\\psi = 0$ (in natural units).",
    "category": "closed_qa"
  },
  {
    "instruction": "What are the $\\gamma$ matrices (Gamma matrices)?",
    "context": "Topic 10.",
    "response": "They are $4\\times4$ matrices that satisfy the Clifford algebra $\\{\\gamma^\\mu, \\gamma^\\nu\\} = 2g^{\\mu\\nu}$.",
    "category": "closed_qa"
  },

  # --- CATEGORY: SUMMARIZATION ---
  {
    "instruction": "Summarize the properties of the Dirac Matrices $\\alpha$ and $\\beta$.",
    "context": "Topic 10.",
    "response": "To construct a linear relativistic Hamiltonian $H = c\\vec{\\alpha}\\cdot\\vec{p} + \\beta mc^2$, the coefficients $\\alpha_i$ and $\\beta$ cannot be numbers; they must be matrices. They must be Hermitian (for real energy), their squares must be the identity matrix, and they must anticommute with each other ($\\{\\alpha_i, \\alpha_j\\} = 0$, $\\{\\alpha_i, \\beta\\} = 0$). The smallest dimension that satisfies this is $4\\times4$.",
    "category": "summarization"
  },
  {
    "instruction": "Summarize the prediction of Spin from the Dirac Equation.",
    "context": "Topic 10.",
    "response": "Unlike the Schrödinger equation where spin is added ad-hoc, the Dirac equation requires the wavefunction to have multi-components (spinors) to satisfy relativistic invariance. When the non-relativistic limit of the Dirac equation is taken (Pauli equation), a term naturally emerges resembling the interaction of a magnetic moment with a field ($\vec{\\sigma} \cdot \vec{B}$), with a g-factor of 2. Thus, spin 1/2 is a natural consequence of uniting relativity and quantum mechanics.",
    "category": "summarization"
  },

  # --- CATEGORY: INFORMATION_EXTRACTION ---
  {
    "instruction": "Extract the form of the Dirac Hamiltonian.",
    "context": "Topic 10.",
    "response": "{\n  \"Hamiltonian\": \"$\\hat{H}_D = c \\vec{\\alpha} \\cdot \\hat{p} + \\beta m c^2$\"\n}",
    "category": "information_extraction"
  },
  {
    "instruction": "Identify the components of a plane wave solution for a resting electron.",
    "context": "Topic 10.",
    "response": "{\n  \"Positive Energy\": \"(1, 0, 0, 0) and (0, 1, 0, 0)\",\n  \"Negative Energy\": \"(0, 0, 1, 0) and (0, 0, 0, 1)\"\n}",
    "category": "information_extraction"
  },

  # --- CATEGORY: CLASSIFICATION ---
  {
    "instruction": "Classify the equations of quantum mechanics.",
    "context": "Topic 10.",
    "response": "{\n  \"Schrödinger\": \"Non-relativistic, Spin 0 (or ad-hoc spin).\",\n  \"Klein-Gordon\": \"Relativistic, Spin 0.\",\n  \"Dirac\": \"Relativistic, Spin 1/2.\"\n}",
    "category": "classification"
  },
  {
    "instruction": "Classify the components of the Dirac spinor $\\psi$.",
    "context": "Topic 10.",
    "response": "{\n  \"Large Components\": \"Electron components (at low velocity).\",\n  \"Small Components\": \"Positron/Relativistic mixing components.\"\n}",
    "category": "classification"
  },

  # --- CATEGORY: BRAINSTORMING ---
  {
    "instruction": "Brainstorm consequences of the Dirac Equation.",
    "context": "",
    "response": "-   Existence of Antimatter (Positrons).\n-   Explanation of Spin 1/2.\n-   Correct fine structure of Hydrogen.\n-   Klein Paradox (tunneling leads to pair production).\n-   Basis for Quantum Electrodynamics (QED).",
    "category": "brainstorming"
  },

  # --- CATEGORY: CREATIVE_WRITING ---
  {
    "instruction": "Write a short monologue for a Positron.",
    "context": "Topic 10.",
    "response": "They call me a 'hole' in the sea, a missing piece of the vacuum. How rude. I am as real as my brother, the electron. I have his mass, his spin, but I carry the positive charge. When we meet, we do not shake hands; we annihilate. We return to pure light. I am the mirror image, the time-reversed echo, the necessary balance to the universe.",
    "category": "creative_writing"
  },

  # --- CATEGORY: GENERATION ---
  {
    "instruction": "Generate the standard representation of the Beta matrix.",
    "context": "Topic 10.",
    "response": "$\\beta = \\begin{pmatrix} I & 0 \\\\ 0 & -I \\end{pmatrix}$",
    "category": "generation"
  },
  {
    "instruction": "Generate the probability current density for the Dirac equation.",
    "context": "Topic 10.",
    "response": "$j^\\mu = \\bar{\\psi} \\gamma^\\mu \\psi$",
    "category": "generation"
  }
]

<>:447: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
<>:491: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
<>:1002: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
<>:447: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
<>:491: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
<>:1002: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
C:\Users\isadmin\AppData\Local\Temp\ipykernel_10176\12726721.py:447: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
  "instruction": "Extract the completeness relation (resolution of identity) for a discrete basis $\{|a_n\\rangle\}$.",
C:\Users\isadmin\AppData\Local\Temp\ipykernel_10176\12726721.py:491: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
  "instruction": "Generate the matrix element notation for an operator $\\hat{A}$ in basis $\{|n\\rangle\}$.",
C:\Users\isadmin\AppData\Local\Temp\ipykernel_10176\12726721.py:1002: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
  "response": "Unlike the Schrödinger equation where spin is added ad-hoc, the Dirac equation requires the wavefunction to have multi-components (spinors) to satisfy relativistic invariance. When the non-relativistic limit of the Dirac equation is taken (Pauli equation), a term naturally emerges resembling the interaction of a magnetic moment with a field ($\vec{\\sigma} \cdot \vec{B}$), with a g-factor of 2. Thus, spin 1/2 is a natural consequence of uniting relativity and quantum mechanics.",

In [3]:
# Ejecutar la exportación
export_list_to_local(L+F, "x.json")

✅ Archivo exportado exitosamente a: c:\Users\isadmin\Desktop\News\x.json

# MoI: Análisis Geométrico y Calidad de Generación en un Diseño Experimental incorporando LoRA con cuantización y retención de información.

In [5]:
import os
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    import subprocess, sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "python-dotenv", "-q"])
    from dotenv import load_dotenv
    load_dotenv()

import os, sys, subprocess, warnings, shutil, gc, math, random, json, time; from itertools import product; from typing import Dict, Any, List, Optional, Tuple
def install_packages(): print("Installing scientific dependencies..."); subprocess.check_call([sys.executable, "-m", "pip", "install", "transformers", "datasets", "peft", "torch", "accelerate", "pandas", "matplotlib", "seaborn", "scipy", "tqdm", "scikit-learn", "openpyxl", "-q"])
try: import peft, torch, seaborn as sns; from transformers import AutoModelForCausalLM
except ImportError: install_packages(); import peft, torch, seaborn as sns; from transformers import AutoModelForCausalLM
import pandas as pd, numpy as np, matplotlib.pyplot as plt, matplotlib.gridspec as gridspec
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer
from transformers.pytorch_utils import Conv1D
from datasets import load_dataset, Dataset
from peft import LoraConfig, get_peft_model
from tqdm.notebook import tqdm
#from google.colab import drive
#dataset in json
X='x.json'
#if not os.path.exists('/content/drive'): print("Mounting Google Drive..."); drive.mount('/content/drive', force_remount=True)
plt.rcParams.update({"font.family": "serif", "axes.labelsize": 12, "font.size": 11, "legend.fontsize": 10, "xtick.labelsize": 10, "ytick.labelsize": 10, "figure.figsize": [10, 7], "mathtext.fontset": "cm", "image.cmap": "viridis", "axes.grid": True, "grid.alpha": 0.3}); warnings.filterwarnings('ignore')
BASE_DRIVE_PATH = os.getcwd()
DATASET_FILENAME = X
DATASET_FULL_PATH = os.path.join(BASE_DRIVE_PATH, DATASET_FILENAME)
device = "cuda" if torch.cuda.is_available() else "cpu"; os.makedirs(BASE_DRIVE_PATH, exist_ok=True)
FULL_GRID = [{'repetition_penalty': rp, 'no_repeat_ngram_size': ng, 'temperature': t, 'top_k': k} for rp in [1.0, 1.2] for ng in [2, 3] for t in [0.7, 1.0] for k in [20, 50]]
QUICK_CONFIG = {"run_config": {"experiment_name": "Exp_MoI_Quick", "num_replicas": 100, "device": device}, "data_config": {"dataset_path": DATASET_FULL_PATH, "finetune_budget": 150, "max_seq_len": 128}, "model_config": {"base_model_id": "openai-community/gpt2", "lora_config": {"r": 16, "lora_alpha": 32, "target_modules": ["c_attn"]}}, "training_config": {"max_steps": 50, "learning_rate": 5e-5, "per_device_train_batch_size": 8, "logging_steps": 5}, "rlct_config": {"max_rlct_estimation_steps": 100, "sgld_lr": 5e-5}, "moi_grid": FULL_GRID}
MID_MID_CONFIG = {"run_config": {"experiment_name": "Exp_MoI_mid_mid", "num_replicas": 1, "device": device, "seed_strategy": "fixed"}, "data_config": {"dataset_path": DATASET_FULL_PATH, "finetune_budget": 250, "max_seq_len": 160, "stratify_by": ["category"]}, "model_config": {"base_model_id": "openai-community/gpt2", "lora_config": {"r": 20, "lora_alpha": 40, "target_modules": ["c_attn"], "init_scale": 0.01}}, "training_config": {"max_steps": 80, "learning_rate": 4e-5, "per_device_train_batch_size": 8, "logging_steps": 8, "warmup_steps": 8}, "rlct_config": {"max_rlct_estimation_steps": 160, "sgld_lr": 4e-5, "burn_in_steps": 20, "beta_schedule": "linear"}, "moi_grid": FULL_GRID + [{'repetition_penalty': rp, 'no_repeat_ngram_size': ng, 'temperature': t, 'top_k': k} for rp in [1.05, 1.15, 1.25] for ng in [2, 3, 4] for t in [0.6, 0.8, 1.0, 1.1] for k in [15, 35, 60, 85]][:12]}
MID_CONFIG = {"run_config": {"experiment_name": "Exp_MoI_mid", "num_replicas": 2, "device": device}, "data_config": {"dataset_path": DATASET_FULL_PATH, "finetune_budget": 400, "max_seq_len": 192}, "model_config": {"base_model_id": "openai-community/gpt2", "lora_config": {"r": 24, "lora_alpha": 48, "target_modules": ["c_attn", "c_proj"]}}, "training_config": {"max_steps": 120, "learning_rate": 3e-5, "per_device_train_batch_size": 8, "logging_steps": 10, "warmup_steps": 12}, "rlct_config": {"max_rlct_estimation_steps": 250, "sgld_lr": 3e-5, "beta_schedule": "geometric"}, "moi_grid": FULL_GRID + [{'repetition_penalty': 1.1, 'no_repeat_ngram_size': 2, 'temperature': 0.85, 'top_k': 35}, {'repetition_penalty': 1.3, 'no_repeat_ngram_size': 4, 'temperature': 0.6, 'top_k': 75}]}
PRE_DEEP_CONFIG = {"run_config": {"experiment_name": "Exp_MoI_pre_deep", "num_replicas": 3, "device": device, "seed_strategy": "linear"}, "data_config": {"dataset_path": DATASET_FULL_PATH, "finetune_budget": 650, "max_seq_len": 224, "stratify_by": ["category", "length"], "augmentation": "synonym_replace"}, "model_config": {"base_model_id": "openai-community/gpt2", "lora_config": {"r": 36, "lora_alpha": 72, "target_modules": ["c_attn", "c_proj"], "lora_dropout": 0.02, "use_rslora": False}}, "training_config": {"max_steps": 200, "learning_rate": 2.5e-5, "per_device_train_batch_size": 6, "gradient_accumulation_steps": 2, "logging_steps": 15, "warmup_steps": 20, "lr_scheduler_type": "linear", "weight_decay": 0.005}, "rlct_config": {"max_rlct_estimation_steps": 400, "sgld_lr": 2.5e-5, "burn_in_steps": 50, "thinning_factor": 2, "beta_schedule": "geometric", "num_chains": 1}, "moi_grid": FULL_GRID + [{'repetition_penalty': rp, 'no_repeat_ngram_size': ng, 'temperature': t, 'top_k': k} for rp in [1.05, 1.15, 1.25] for ng in [2, 3, 4] for t in [0.6, 0.8, 1.0, 1.1] for k in [15, 35, 60, 85]][:24], "analysis_config": {"compute_hessian_spectrum": False, "svd_analysis_frequency": 100, "checkpoint_frequency": 50}}
DEEP_CONFIG = {"run_config": {"experiment_name": "Exp_MoI_deep", "num_replicas": 4, "device": device, "seed_strategy": "orthogonal"}, "data_config": {"dataset_path": DATASET_FULL_PATH, "finetune_budget": 1000, "max_seq_len": 256, "stratify_by": ["category", "length"]}, "model_config": {"base_model_id": "openai-community/gpt2-medium", "lora_config": {"r": 48, "lora_alpha": 96, "target_modules": ["c_attn", "c_proj", "c_fc"], "lora_dropout": 0.05}}, "training_config": {"max_steps": 300, "learning_rate": 2e-5, "per_device_train_batch_size": 4, "gradient_accumulation_steps": 4, "logging_steps": 20, "warmup_steps": 30, "lr_scheduler_type": "cosine", "weight_decay": 0.01}, "rlct_config": {"max_rlct_estimation_steps": 600, "sgld_lr": 2e-5, "burn_in_steps": 100, "thinning_factor": 3, "beta_schedule": "adaptive", "num_chains": 2}, "moi_grid": FULL_GRID + [{'repetition_penalty': rp, 'no_repeat_ngram_size': ng, 'temperature': t, 'top_k': k, 'top_p': p} for rp in [1.0, 1.15, 1.3] for ng in [2, 3, 4] for t in [0.5, 0.7, 0.85, 1.0, 1.2] for k in [10, 25, 50, 75, 100] for p in [0.9, 0.95, 1.0]], "analysis_config": {"compute_hessian_spectrum": True, "svd_analysis_frequency": 50, "checkpoint_frequency": 100}}
ACTIVE_CONFIG = QUICK_CONFIG
class ExperimentVisualizer:
    def __init__(self, output_dir): self.output_dir = output_dir
    def plot_loss_history(self, log_history, run_id):
        losses = [x['loss'] for x in log_history if 'loss' in x]; steps = [x['step'] for x in log_history if 'loss' in x]
        if losses: plt.figure(figsize=(10, 6)); plt.plot(steps, losses, marker='o', linestyle='-', color='darkblue', linewidth=1.5, label='Training Loss'); plt.yscale('log'); plt.title(f"Run {run_id}: Optimization Convergence $\\mathcal{{L}}(\\theta)$"); plt.xlabel("Training Steps $t$"); plt.ylabel(r"Loss $\log \mathcal{L}$"); plt.legend(); plt.tight_layout(); plt.savefig(os.path.join(self.output_dir, "training_loss_evolution.png")); plt.close()
    def plot_rlct_evolution(self, lambda_history, run_id): plt.figure(figsize=(10, 6)); plt.plot(lambda_history, color='purple', linewidth=1.5); plt.title(rf"Run {run_id}: RLCT Convergence $\lambda_t$ (WBIC)"); plt.xlabel("SGLD Steps (Cumulative)"); plt.ylabel(r"Estimated RLCT $\hat{\lambda}$"); plt.grid(True, which="both", alpha=0.3); plt.tight_layout(); plt.savefig(os.path.join(self.output_dir, "rlct_evolution_lambda.png")); plt.close()
    def plot_kl_divergence(self, energy_history, run_id): deltas = np.abs(np.diff(energy_history)); plt.figure(figsize=(10, 6)); plt.plot(deltas, color='teal', alpha=0.7, linewidth=1); plt.title(rf"Run {run_id}: Local Divergence $\Delta \mathcal{{L}} \approx |E_t - E_{{t-1}}|$"); plt.xlabel("SGLD Steps"); plt.ylabel(r"Energy Fluctuation"); plt.yscale('log'); plt.tight_layout(); plt.savefig(os.path.join(self.output_dir, "rlct_kl_divergence.png")); plt.close()
    def plot_moi_analysis(self, df, run_id):
        if df.empty: return
        fig, axes = plt.subplots(2, 2, figsize=(14, 10)); fig.suptitle(f"Run {run_id}: MoI Sensitivity Analysis (Factorial)", fontsize=14); factors = [('temperature', r'Temperature $T$'), ('repetition_penalty', r'Repetition Penalty $\rho$'), ('top_k', r'Top-K'), ('no_repeat_ngram_size', r'N-Gram Block')]
        for ax, (col, label) in zip(axes.flatten(), factors):
            if col in df.columns: sns.boxplot(x=col, y='ppl', data=df, ax=ax, palette="viridis"); ax.set_xlabel(label); ax.set_ylabel(r"Perplexity $PPL_{MoI}$ (Log)"); ax.set_yscale('log')
        plt.tight_layout(rect=[0, 0.03, 1, 0.95]); plt.savefig(os.path.join(self.output_dir, "moi_boxplots_factorial.png")); plt.close()
        if 'temperature' in df.columns and 'repetition_penalty' in df.columns:
            try: pivot = df.pivot_table(index='temperature', columns='repetition_penalty', values='ppl', aggfunc='mean'); plt.figure(figsize=(8, 6)); sns.heatmap(pivot, annot=True, fmt=".1f", cmap="viridis_r", cbar_kws={'label': 'Mean PPL'}); plt.title(f"Run {run_id}: MoI Stability Landscape ($T$ vs $\\rho$)"); plt.xlabel(r'Repetition Penalty $\rho$'); plt.ylabel(r'Temperature $T$'); plt.tight_layout(); plt.savefig(os.path.join(self.output_dir, "moi_heatmap_interaction.png")); plt.close()
            except: pass
class ExperimentDocumentationGenerator:
    def __init__(self, output_dir, config): self.doc_dir = os.path.join(output_dir, "Mathematical_Supplement"); os.makedirs(self.doc_dir, exist_ok=True)
    def generate_all(self): self._write_math(); print(f"   -> Documentation saved to: {self.doc_dir}")
    def _write_math(self):
        content = r"""soon..."""
        with open(os.path.join(self.doc_dir, "01_Math_Foundations.txt"), "w") as f: f.write(content)
class ElasticLoraLayer(torch.nn.Module):
    def __init__(self, original_layer, r, lora_alpha, lora_dropout):
        super().__init__(); self.original_layer = original_layer; self.scaling = lora_alpha / r; in_features, out_features = (original_layer.weight.shape if isinstance(original_layer, Conv1D) else original_layer.weight.shape[::-1] if isinstance(original_layer, torch.nn.Linear) else sorted(original_layer.weight.shape)); self.lora_A = torch.nn.Linear(in_features, r, bias=False); self.lora_B = torch.nn.Linear(r, out_features, bias=False); self.lora_dropout = torch.nn.Dropout(p=lora_dropout); self.beta = torch.nn.Parameter(torch.ones(1) * 0.01); torch.nn.init.kaiming_uniform_(self.lora_A.weight, a=math.sqrt(5)); torch.nn.init.zeros_(self.lora_B.weight)
    def forward(self, x):
        with torch.no_grad(): base_out = self.original_layer(x)
        return base_out + (self.lora_B(self.lora_A(self.lora_dropout(x))) * self.scaling) + (self.beta * x.mean(dim=-1, keepdim=True))
class SingularLearningEstimator:
    class SGLD(torch.optim.Optimizer):
        def __init__(self, params, lr, num_samples, temperature): super().__init__(params, dict(lr=lr, num_samples=num_samples, temperature=temperature))
        def step(self):
            for group in self.param_groups:
                for p in group['params']:
                    if p.grad is not None: noise = torch.normal(0, math.sqrt(group['lr']), p.size(), device=p.device); p.data.add_(p.grad, alpha=-0.5 * group['lr'] * (group['num_samples']/group['temperature'])); p.data.add_(noise)
    @staticmethod
    def estimate_rlct_wbic(model, tokenizer, dataset, config):
        n = len(dataset); beta1, beta2 = 1.0/np.log(n), 1.5/np.log(n); optimizer = SingularLearningEstimator.SGLD(model.parameters(), lr=config['sgld_lr'], num_samples=n, temperature=1.0/beta1); energies, lambdas = [], []; model.train()
        for _ in tqdm(range(config['max_rlct_estimation_steps']), desc="WBIC SGLD", leave=False):
            batch = dataset.select(np.random.choice(n, 4))
            txt = [f"{x['instruction']}\n{x['response']}" for x in batch]
            inputs = tokenizer(txt, truncation=True, padding="max_length", max_length=64, return_tensors="pt").to(model.device)
            optimizer.zero_grad()
            loss = model(**inputs, labels=inputs.input_ids).loss
            if loss is None or torch.isnan(loss): continue
            loss.backward(); optimizer.step(); curr_energy = loss.item() * n; energies.append(curr_energy)
            if len(energies) > 10: vals = np.array(energies); log_w = -(beta2 - beta1) * vals; w = np.exp(log_w - np.max(log_w)); lambdas.append((np.mean(vals) - (np.sum(w * vals) / np.sum(w))) / (1/beta1 - 1/beta2))
            else: lambdas.append(0)
        return (lambdas[-1] if lambdas else 0.0), energies, lambdas
class MoIEvaluator:
    def __init__(self, model, tokenizer, grid): self.model, self.tok, self.grid = model, tokenizer, grid
    def run(self, prompt, device):
        res = []; inp = self.tok(prompt, return_tensors="pt").input_ids.to(device)
        for p in self.grid:
            try:
                with torch.no_grad(): gen = self.model.generate(inp, max_new_tokens=40, do_sample=True, pad_token_id=self.tok.eos_token_id, **p); txt = self.tok.decode(gen[0], skip_special_tokens=True); target = self.tok(txt, return_tensors="pt").input_ids.to(device); loss = self.model(target, labels=target).loss; ppl = torch.exp(loss).item() if target.shape[1] > 1 else 1000.0
            except: ppl = float('inf')
            res.append({**p, 'ppl': ppl})
        return pd.DataFrame(res)
def prepare_data(config):
    # This forces the use of the dummy DataFrame structure
    return pd.DataFrame({"instruction": ["Explain AI", "Solve 1+1"]*50, "response": ["AI is code", "2"]*50})

def apply_iec(model):
    for name, mod in model.named_modules():
        if isinstance(mod, (torch.nn.Linear, Conv1D)) and "c_attn" in name: parent = model.get_submodule(name.rsplit('.', 1)[0]); setattr(parent, name.rsplit('.', 1)[1], ElasticLoraLayer(mod, 8, 16, 0.1).to(mod.weight.device))
    return model
def verify_grads(model):
    if sum(p.numel() for p in model.parameters() if p.requires_grad) == 0: raise RuntimeError("No trainable params!")
def run_experiment(config):
    run_cfg = config['run_config']; out_dir = os.path.join(BASE_DRIVE_PATH, run_cfg['experiment_name']); shutil.rmtree(out_dir) if os.path.exists(out_dir) else None; os.makedirs(out_dir, exist_ok=True); visualizer = ExperimentVisualizer(out_dir); doc_gen = ExperimentDocumentationGenerator(out_dir, config)
    # Ensure ds is a Hugging Face Dataset
    df_data = prepare_data(config)
    ds = Dataset.from_pandas(df_data)

    tokenizer = AutoTokenizer.from_pretrained(config['model_config']['base_model_id']); tokenizer.pad_token = tokenizer.eos_token if not tokenizer.pad_token else tokenizer.pad_token; results = []
    for replica in range(run_cfg['num_replicas']):
        for mode in ["Standard_LoRA", "Elastic_IEC"]:
            run_id = f"Rep{replica}_{mode}"; print(f"\n{run_id}"); run_path = os.path.join(out_dir, run_id); os.makedirs(run_path, exist_ok=True); visualizer.output_dir = run_path; model = AutoModelForCausalLM.from_pretrained(config['model_config']['base_model_id']).to(run_cfg['device'])
            if mode == "Standard_LoRA": model = get_peft_model(model, LoraConfig(r=8, lora_alpha=16, target_modules=["c_attn"], task_type="CAUSAL_LM"))
            else: model = apply_iec(model); [setattr(p, 'requires_grad', False) for n, p in model.named_parameters() if "lora" not in n and "beta" not in n]
            verify_grads(model); lam, energies, lam_hist = SingularLearningEstimator.estimate_rlct_wbic(model, tokenizer, ds, config['rlct_config']); visualizer.plot_rlct_evolution(lam_hist, run_id); visualizer.plot_kl_divergence(energies, run_id); print(f"   lambda = {lam:.2f}")
            args = TrainingArguments(output_dir=os.path.join(run_path, "ckpt"), max_steps=config['training_config']['max_steps'], learning_rate=config['training_config']['learning_rate'], logging_steps=5, report_to="none", save_strategy="no", remove_unused_columns=False)
            def collate(b): txt = [f"{x['instruction']}\n{x['response']}" for x in b]; enc = tokenizer(txt, padding="max_length", truncation=True, max_length=64, return_tensors="pt"); enc['labels'] = enc['input_ids'].clone(); return enc
            trainer = Trainer(model=model, args=args, train_dataset=ds, data_collator=collate); trainer.train(); visualizer.plot_loss_history(trainer.state.log_history, run_id); moi_df = MoIEvaluator(model, tokenizer, config['moi_grid']).run(ds[0]['instruction'], run_cfg['device']); visualizer.plot_moi_analysis(moi_df, run_id); results.append({"Run": run_id, "Lambda": lam, "Min_PPL": moi_df['ppl'].min()}); del model, trainer; gc.collect(); torch.cuda.empty_cache()
    pd.DataFrame(results).to_csv(os.path.join(out_dir, "results.csv")); doc_gen.generate_all(); return out_dir
if __name__ == "__main__": path = run_experiment(ACTIVE_CONFIG); print(f"DONE. Saved to: {path}")

Rep0_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 77.92

Rep0_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 78.08

Rep1_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 94.48

Rep1_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 42.82

Rep2_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 40.55

Rep2_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 51.97

Rep3_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 120.74

Rep3_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 142.22

Rep4_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 109.95

Rep4_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 89.98

Rep5_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 68.31

Rep5_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 71.23

Rep6_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 102.25

Rep6_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 109.74

Rep7_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 97.70

Rep7_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 82.44

Rep8_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 98.98

Rep8_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 85.04

Rep9_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 89.58

Rep9_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 62.10

Rep10_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 63.47

Rep10_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 62.59

Rep11_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 90.01

Rep11_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 53.51

Rep12_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 102.75

Rep12_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 49.33

Rep13_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 67.06

Rep13_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 79.15

Rep14_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 56.82

Rep14_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 69.00

Rep15_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 90.86

Rep15_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 40.88

Rep16_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 86.39

Rep16_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 71.20

Rep17_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 70.21

Rep17_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 56.14

Rep18_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 101.45

Rep18_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 61.49

Rep19_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 72.84

Rep19_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 105.21

Rep20_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 71.16

Rep20_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 62.07

Rep21_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 85.76

Rep21_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 55.46

Rep22_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 69.43

Rep22_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 62.05

Rep23_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 116.44

Rep23_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 93.60

Rep24_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 59.67

Rep24_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 63.10

Rep25_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 55.27

Rep25_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 84.48

Rep26_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 84.01

Rep26_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 67.83

Rep27_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 72.13

Rep27_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 42.31

Rep28_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 50.68

Rep28_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 72.28

Rep29_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 89.18

Rep29_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 99.04

Rep30_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 105.98

Rep30_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 65.91

Rep31_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 84.09

Rep31_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 46.61

Rep32_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 99.63

Rep32_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 95.31

Rep33_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 92.49

Rep33_Elastic_IEC

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

   lambda = 73.94

Rep34_Standard_LoRA

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

WBIC SGLD:   0%|          | 0/100 [00:00<?, ?it/s]

KeyboardInterrupt:

# LoT Análisis Geométrico y Dinámica de Generación en un Diseño Experimental incorporando LoRA con rango extremadamente pequeño

In [2]:
import os
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    import subprocess, sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "python-dotenv", "-q"])
    from dotenv import load_dotenv
    load_dotenv()

import os, sys, subprocess, warnings, gc, math, random, shutil, json, torch, numpy as np, pandas as pd, matplotlib.pyplot as plt, matplotlib as mpl, seaborn as sns, spacy
from itertools import product; from typing import Dict, Any, List; from google.colab import drive
from mpl_toolkits.mplot3d import Axes3D; from mpl_toolkits.mplot3d.art3d import Line3DCollection
from scipy.linalg import svd as scipy_svd; from scipy.stats import kurtosis, gaussian_kde
from scipy.optimize import linear_sum_assignment; from tqdm.notebook import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from datasets import load_dataset, Dataset; from peft import LoraConfig, get_peft_model
# dataset in json
X='x.json'
def install_packages_if_needed():
    try: import peft, spacy, xlsxwriter, statsmodels
    except ImportError: subprocess.check_call([sys.executable, "-m", "pip", "install", "transformers", "datasets", "peft", "torch", "accelerate", "statsmodels", "pandas", "spacy", "matplotlib", "scipy", "tqdm", "xlsxwriter", "-q"]); subprocess.call([sys.executable, "-m", "spacy", "download", "en_core_web_sm", "-q"])

install_packages_if_needed(); nlp = spacy.load("en_core_web_sm") if 'spacy' in sys.modules else lambda x: x
try: drive.mount('/content/drive', force_remount=True)
except: pass
warnings.filterwarnings('ignore'); plt.rcParams.update({"font.family": "serif", "font.serif": ["cmr10", "DejaVu Serif", "Bitstream Vera Serif"], "mathtext.fontset": "cm", "axes.labelsize": 14, "font.size": 12, "legend.fontsize": 12, "xtick.labelsize": 12, "ytick.labelsize": 12, "figure.figsize": [10, 8], "image.cmap": "jet", "axes.formatter.use_mathtext": True})
BASE_DRIVE_PATH = '/content/drive/My Drive/University_MATH'; DATASET_FILENAME = X; DATASET_FULL_PATH = os.path.join(BASE_DRIVE_PATH, DATASET_FILENAME)

QUICK_CONFIG = {"run_config": {"experiment_name": "Exp_Quick", "num_replicas": 1, "device": "cuda"}, "data_config": {"dataset_path": DATASET_FULL_PATH, "linguistic_sample_size": 100, "finetune_budget": 10, "max_seq_len": 64}, "model_config": {"base_model_id": "openai-community/gpt2", "lora_config": {"r": 4, "lora_alpha": 8, "target_modules": ["c_attn"]}}, "training_config": {"max_steps": 5, "learning_rate": 1e-4, "per_device_train_batch_size": 4, "logging_steps": 2}, "rlct_config": {"max_rlct_estimation_steps": 5, "sgld_lr": 1e-4}, "lot_config": {"use_alternating_source": True, "dolly_lot_sample_size": 10, "n_tokens": 10, "num_trajectories": 10}}
INTERMEDIATE_CONFIG = {"run_config": {"experiment_name": "Exp_PhD_2_Intermediate", "num_replicas": 1, "device": "cuda"}, "data_config": {"dataset_path": DATASET_FULL_PATH, "linguistic_sample_size": 1000, "finetune_budget": 50, "max_seq_len": 128}, "model_config": {"base_model_id": "openai-community/gpt2", "lora_config": {"r": 8, "lora_alpha": 16, "target_modules": ["c_attn"]}}, "training_config": {"max_steps": 20, "learning_rate": 5e-5, "per_device_train_batch_size": 4, "logging_steps": 5}, "rlct_config": {"max_rlct_estimation_steps": 15, "sgld_lr": 1e-4}, "lot_config": {"use_alternating_source": True, "dolly_lot_sample_size": 30, "n_tokens": 20, "num_trajectories": 50}}
DEEP_CONFIG = {"run_config": {"experiment_name": "Exp_PhD_3_Deep", "num_replicas": 2, "device": "cuda"}, "data_config": {"dataset_path": DATASET_FULL_PATH, "linguistic_sample_size": 5000, "finetune_budget": 150, "max_seq_len": 128}, "model_config": {"base_model_id": "openai-community/gpt2", "lora_config": {"r": 16, "lora_alpha": 32, "target_modules": ["c_attn"]}}, "training_config": {"max_steps": 50, "learning_rate": 5e-5, "per_device_train_batch_size": 8, "logging_steps": 10}, "rlct_config": {"max_rlct_estimation_steps": 50, "sgld_lr": 5e-5}, "lot_config": {"use_alternating_source": True, "dolly_lot_sample_size": 100, "n_tokens": 30, "num_trajectories": 100}}
ACTIVE_CONFIG = QUICK_CONFIG

class ExperimentDocumentationGenerator:
    def __init__(self, output_dir, config): self.base_dir, self.doc_dir, self.config = output_dir, os.path.join(output_dir, "Mathematical_Foundations_and_Analysis"), config; os.makedirs(self.doc_dir, exist_ok=True)
    def generate_all(self): self._write_math_foundations(); self._write_graph_analysis(); self._write_conclusions(); print(f"   -> Documentation saved in: {self.doc_dir}")
    def _write_math_foundations(self):
        with open(os.path.join(self.doc_dir, "01_Mathematical_Foundations.txt"), "w") as f: f.write(r"soon...")
    def _write_graph_analysis(self):
        with open(os.path.join(self.doc_dir, "02_Graphical_Analysis.txt"), "w") as f: f.write(r"soon")
    def _write_conclusions(self):
        with open(os.path.join(self.doc_dir, "03_Conclusions_and_Implications.txt"), "w") as f: f.write(r"soon...")

class SingularLearningEstimator:
    class SGLD(torch.optim.Optimizer):
        def __init__(self, params, lr=1e-3, noise_level=1., temperature=1., num_samples=1, batch_size=1): super().__init__(params, dict(lr=lr, noise_level=noise_level, temperature=temperature, num_samples=num_samples, batch_size=batch_size))
        def step(self, closure=None):
            for group in self.param_groups:
                for p in group['params']:
                    if p.grad is not None:
                        with torch.no_grad(): p.add_(p.grad * (group["num_samples"] / group["batch_size"]), alpha=-0.5 * group['lr'] / group['temperature']); p.add_(torch.normal(mean=0., std=group['noise_level'], size=p.grad.size(), device=p.grad.device), alpha=math.sqrt(group['lr']))
    @staticmethod
    def estimate_rlct(model, tokenizer, dataset, config):
        print("   -> RLCT Phase: WBIC Estimation (Watanabe 2013)..."); n = len(dataset); beta1, beta2 = 1.0/np.log(n), 1.5/np.log(n); optimizer = SingularLearningEstimator.SGLD(model.parameters(), lr=config['sgld_lr'], num_samples=n, batch_size=1, temperature=1.0/beta1); energies = []; model.eval()
        for i in tqdm(range(min(n, config['max_rlct_estimation_steps'])), desc="WBIC Sampling", leave=False):
            inputs = tokenizer(f"{dataset[i%n]['instruction']}\n{dataset[i%n]['response']}", truncation=True, max_length=config["max_seq_len"], return_tensors="pt").to(config['device']); model.train(); optimizer.zero_grad(); loss = model(**inputs, labels=inputs.input_ids).loss; loss.backward(); optimizer.step(); model.eval(); energies.append(loss.item() * n)
        if not energies: return 0.0, model, []
        V = np.array(energies); E_b1 = np.mean(V); log_w = -(beta2 - beta1) * V; norm_w = np.exp(log_w - np.max(log_w)); E_b2 = np.sum((norm_w/np.sum(norm_w)) * V); return (E_b1 - E_b2) / ((1.0/beta1) - (1.0/beta2)), model, [e/n for e in energies]

class ScientificLoTSuite:
    def __init__(self, model, tokenizer, output_dir): self.model, self.tokenizer, self.output_dir = model, tokenizer, output_dir; os.makedirs(output_dir, exist_ok=True); self.model.eval()
    def generate_trajectories(self, text, lot_config):
        print(f"   -> Generating {lot_config['num_trajectories']} LoT trajectories..."); tokens = self.tokenizer(text, return_tensors='pt', truncation=True, max_length=1024).input_ids[0]; sentences = [tokens[i:i+lot_config['n_tokens']] for i in range(0,len(tokens)-lot_config['n_tokens']+1, lot_config['n_tokens'])][:lot_config['num_trajectories']]
        if not sentences: return None
        trajectories = []
        with torch.no_grad():
            for s in tqdm(sentences, desc="Tracing", leave=False): trajectories.append(np.stack([h[0,-1,:].float().cpu().numpy() for h in self.model(s.unsqueeze(0).to(self.model.device), output_hidden_states=True).hidden_states], axis=1))
        return np.stack(trajectories, axis=2)[:, 1:, :] if trajectories else None
    def _plot_ribbon_trajectories(self, traj):
        h, l, s = traj.shape; flat = traj.reshape(h, -1).astype(np.float32)
        try: U, S, V = scipy_svd(flat, full_matrices=False)
        except: return
        proj = (np.diag(S[:3]) @ V[:3, :]).reshape(3, l, s); fig = plt.figure(figsize=(10, 8)); ax = fig.add_subplot(111, projection='3d'); cmap = plt.get_cmap('jet', l)
        for i in range(min(s, 50)): points = np.array([proj[0,:,i], proj[1,:,i], proj[2,:,i]]).T.reshape(-1, 1, 3); ax.add_collection(Line3DCollection(np.concatenate([points[:-1], points[1:]], axis=1), cmap=cmap, norm=plt.Normalize(0, l), alpha=0.4, linewidth=0.8))
        ax.set_xlim(proj[0].min(), proj[0].max()); ax.set_ylim(proj[1].min(), proj[1].max()); ax.set_zlim(proj[2].min(), proj[2].max()); ax.set_xlabel(r'$\mathbf{u}_1$', labelpad=10); ax.set_ylabel(r'$\mathbf{u}_2$', labelpad=10); ax.set_zlabel(r'$\mathbf{u}_3$', labelpad=10); ax.set_title(r'Lines of Thought Manifold (PCA)', y=1.02); ax.grid(False); fig.colorbar(plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(0, l)), ax=ax, shrink=0.6, pad=0.1).set_label(r'Layer Depth $t$', rotation=270, labelpad=20); plt.savefig(f"{self.output_dir}/lot_manifold_pca_projection.png", dpi=300, bbox_inches='tight'); plt.close()
    def _plot_coordinate_manifold(self, traj):
        h, l, s = traj.shape; vars_dim = np.var(traj.reshape(h, -1), axis=1); top = np.argsort(vars_dim)[-3:]; fig = plt.figure(figsize=(10, 8)); ax = fig.add_subplot(111, projection='3d'); cmap = plt.get_cmap('viridis', l)
        for t in range(l): ax.scatter(traj[top[0], t, ::2], traj[top[1], t, ::2], traj[top[2], t, ::2], color=cmap(t), s=3, alpha=0.6)
        ax.set_xlabel(rf'$\mathbf{{e}}_{{{top[0]}}}$'); ax.set_ylabel(rf'$\mathbf{{e}}_{{{top[1]}}}$'); ax.set_zlabel(rf'$\mathbf{{e}}_{{{top[2]}}}$'); ax.set_title(r'Manifold in Coordinate Basis', y=1.02); fig.colorbar(plt.cm.ScalarMappable(cmap=cmap, norm=mpl.colors.Normalize(vmin=0, vmax=l)), ax=ax, shrink=0.6, pad=0.1).set_label(r'Layer Depth $t$', rotation=270, labelpad=20); plt.savefig(f"{self.output_dir}/lot_coordinate_basis_projection.png", dpi=300, bbox_inches='tight'); plt.close()
    def _plot_sv_angles(self, traj):
        n = traj.shape[1]; us = [scipy_svd(traj[:,t,:].astype(np.float32), full_matrices=False)[0] for t in range(n)]; fig, axes = plt.subplots(2, 2, figsize=(12, 10)); fig.suptitle(r'Angle $\arccos(\mathbf{u}_i^{(t_1)} \cdot \mathbf{u}_i^{(t_2)})$', y=0.95, fontsize=16)
        for i in range(4):
            mat = np.array([[np.degrees(np.arccos(np.clip(np.abs(np.dot(us[t1][:, i], us[t2][:, i])), -1.0, 1.0))) for t2 in range(n)] for t1 in range(n)])
            im = axes[i//2, i%2].imshow(mat, cmap='viridis', origin='lower', vmin=0, vmax=90); axes[i//2, i%2].set_title(rf'Singular Vector $u_{i+1}$'); fig.colorbar(im, ax=axes[i//2, i%2], fraction=0.046, pad=0.04).set_label(r'$\theta$ (deg)', rotation=270, labelpad=15)
        plt.tight_layout(rect=[0, 0.03, 1, 0.93]); plt.savefig(f"{self.output_dir}/svd_singular_vector_alignment_angles.png", dpi=300); plt.close()
    def _plot_singular_values(self, traj):
        n = traj.shape[1]; sigs = [scipy_svd(traj[:,t,:].astype(np.float32), full_matrices=False, compute_uv=False) for t in range(n)]; fig, ax = plt.subplots(figsize=(10, 8)); cmap = plt.get_cmap('jet', n)
        for t in range(n): ax.loglog(range(1, len(sigs[t])+1), sigs[t], color=cmap(t), alpha=0.9, linewidth=1.5)
        ax.set_title(r'Singular Value Spectrum'); ax.set_xlabel(r'Rank $k$'); ax.set_ylabel(r'$\sigma_k$'); ax.grid(True, which="both", ls="-", alpha=0.2); fig.colorbar(plt.cm.ScalarMappable(cmap=cmap, norm=mpl.colors.Normalize(vmin=0, vmax=n)), ax=ax).set_label(r'Layer $t$', rotation=270, labelpad=20); plt.savefig(f"{self.output_dir}/svd_singular_value_spectrum_decay.png", dpi=300, bbox_inches='tight'); plt.close()
    def _plot_kl_vs_k(self, traj):
        final = torch.tensor(traj[:, -1, :].T).to(self.model.device).float(); head = self.model.get_output_embeddings().weight.T.float(); kl = []
        with torch.no_grad():
            true_p = torch.softmax(final @ head, dim=-1); U = torch.svd(final.T)[0]; max_rank = min(U.shape[1], final.shape[1], 128); K_dims = np.unique(np.geomspace(1, max(2, max_rank-1), 10, dtype=int))
            for k in K_dims: kl.append(torch.nn.functional.kl_div(torch.log_softmax(((U[:, :k] @ U[:, :k].T) @ final.T).T @ head, dim=-1), true_p, reduction='batchmean').item())
        fig, ax = plt.subplots(figsize=(8, 6)); ax.plot(K_dims, kl, 'k.-', linewidth=1.5); ax.set_title(r'$\langle D_{KL}(\mathbf{p}_K^\nu || \mathbf{p}^\nu) \rangle$ vs Rank $K$'); plt.savefig(f"{self.output_dir}/kl_divergence_information_loss_vs_rank.png", dpi=300); plt.close()
    def _plot_delta_heatmaps(self, traj):
        n = traj.shape[1]; mat_m, mat_v, mat_k = np.full((n,n), np.nan), np.full((n,n), np.nan), np.full((n,n), np.nan)
        for t in range(n):
            for tau in range(1, n - t): d = traj[:, t + tau, :] - traj[:, t, :]; mat_m[t+tau, t] = np.mean(d)/(np.std(d)+1e-9); mat_v[t+tau, t] = np.log(np.var(d)+1e-9); mat_k[t+tau, t] = np.mean(kurtosis(d, axis=1))
        fig, axes = plt.subplots(1, 3, figsize=(18, 5)); labs = [r'$\langle |\mu/\sigma| \rangle$', r'$\langle \log(\sigma^2) \rangle$', r'$\langle |\kappa| \rangle$']; mats = [mat_m, mat_v, mat_k]
        for i in range(3): im = axes[i].imshow(mats[i], cmap='jet', aspect='auto', origin='upper'); axes[i].set_title(labs[i]); fig.colorbar(im, ax=axes[i])
        plt.savefig(f"{self.output_dir}/drift_diffusion_statistics_heatmaps.png", dpi=300, bbox_inches='tight'); plt.close()
    def _plot_kde_residuals(self, traj):
        h, l, s = traj.shape; fig, ax = plt.subplots(figsize=(8, 6)); d8, d10 = traj[:, 8, :] - traj[:, 0, :], traj[:, 10, :] - traj[:, 0, :]
        sns.kdeplot((d8.flatten()-np.mean(d8))/(np.std(d8)+1e-9), ax=ax, label=r'$t+\tau=8$', color='tab:blue'); sns.kdeplot((d10.flatten()-np.mean(d10))/(np.std(d10)+1e-9), ax=ax, label=r'$t+\tau=10$', color='tab:orange')
        x = np.linspace(-5, 5, 100); ax.plot(x, 1/np.sqrt(2*np.pi)*np.exp(-0.5*x**2), 'k--', label='Gaussian'); ax.set_yscale('log'); ax.legend(); plt.savefig(f"{self.output_dir}/residual_distribution_normality_check.png", dpi=300); plt.close()
        try:
            flat = traj.reshape(h, -1).astype(np.float32); U, S, V = scipy_svd(flat, full_matrices=False); proj = (np.diag(S[:2]) @ V[:2, :]).reshape(2, l, s); fig, axes = plt.subplots(2, 5, figsize=(20, 8)); shifts = [6, 7, 8, 9, 10]
            for i, sh in enumerate(shifts):
                if sh < l:
                    for row, t_idx in enumerate([sh, sh-2]):
                        u1, u2 = proj[0, t_idx, :], proj[1, t_idx, :]; k = gaussian_kde([u1, u2]); xi, yi = np.mgrid[u1.min():u1.max():20j, u2.min():u2.max():20j]; axes[row, i].contour(xi, yi, k(np.vstack([xi.flatten(), yi.flatten()])).reshape(xi.shape), cmap='jet')
            plt.savefig(f"{self.output_dir}/probability_density_evolution_contours.png", dpi=300); plt.close()
        except: pass
    def run_full_analysis(self, lot_config, dolly_dataset):
        print(f"   -> Executing LoT Analysis in: {os.path.basename(self.output_dir)}")
        if lot_config.get('use_alternating_source', True): sample = dolly_dataset.shuffle().select(range(min(len(dolly_dataset), 100))); text = "\n\n".join(list(sample['instruction']) + [r for r in sample['response'] if r])
        else: text = " ".join(["thought"] * 500)
        traj = self.generate_trajectories(text, lot_config)
        if traj is not None: [getattr(self, m)(traj) for m in dir(self) if m.startswith('_plot_')]; print("   -> Scientific Charts Generated.")

def plot_training_history(history, run_id, output_dir):
    if history:
        df = pd.DataFrame(history).dropna(subset=['loss']); plt.figure(figsize=(10, 6)); plt.plot(df['step'], df['loss'], marker='o', label='Training Loss'); plt.title(rf"Training Loss Run {run_id}"); plt.yscale('log'); plt.grid(True, alpha=0.3); plt.savefig(os.path.join(output_dir, "training_history_loss.png")); plt.close()

def run_linguistic_anova_experiment(master_config: Dict[str, Any]):
    run_cfg, data_cfg = master_config['run_config'], master_config['data_config']; output_dir = os.path.join("/content", run_cfg['experiment_name']); os.makedirs(output_dir, exist_ok=True); doc_gen = ExperimentDocumentationGenerator(output_dir, master_config)
    try: full_ds = load_dataset('json', data_files=data_cfg['dataset_path'], split='train')
    except: full_ds = Dataset.from_pandas(pd.DataFrame({"instruction": ["Explain AI", "Solve 1+1"]*50, "response": ["AI is code", "2"]*50}))
    subset = full_ds.shuffle(seed=42).select(range(min(data_cfg['linguistic_sample_size'], len(full_ds)))); df = pd.DataFrame([{'syntax': len(t.split()), 'lexicon': len(set(t.split()))/len(t.split()) if t.split() else 0, **subset[i]} for i, t in enumerate([str(t) for t in subset['instruction']])]); b = data_cfg['finetune_budget']; pools = {"Simple Syntax": Dataset.from_pandas(df.sort_values('syntax').head(b)), "Complex Syntax": Dataset.from_pandas(df.sort_values('syntax', ascending=False).head(b)), "Rich Lexicon": Dataset.from_pandas(df.sort_values('lexicon', ascending=False).head(b))}; results, all_rlct = [], []; tokenizer = AutoTokenizer.from_pretrained(master_config['model_config']['base_model_id']); tokenizer.pad_token = tokenizer.eos_token or tokenizer.pad_token; run_counter = 0
    for replica in range(run_cfg['num_replicas']):
        for treat, method in product(pools.keys(), ["Standard LoRA", "Two-Phase LoRA + RLCT"]):
            run_counter += 1; run_id = f"{run_counter}_Rep{replica}_{treat.replace(' ','')}_{method.split()[0]}"; print(f"\nRun {run_id} | {treat} | {method}"); run_dir = os.path.join(output_dir, run_id); os.makedirs(run_dir, exist_ok=True); peft_model = get_peft_model(AutoModelForCausalLM.from_pretrained(master_config['model_config']['base_model_id'], dtype=torch.float32).to(run_cfg['device']), LoraConfig(task_type="CAUSAL_LM", **master_config['model_config']['lora_config'])); rlct_val = np.nan
            if "RLCT" in method: rlct_val, peft_model, losses = SingularLearningEstimator.estimate_rlct(peft_model, tokenizer, pools[treat], {**master_config['rlct_config'], "max_seq_len": data_cfg["max_seq_len"], "device": run_cfg["device"]}); all_rlct.append(pd.DataFrame({'run': run_id, 'loss': losses}))
            trainer = Trainer(model=peft_model, args=TrainingArguments(output_dir=f"{run_dir}/ckpt", report_to="none", save_strategy="no", remove_unused_columns=False, **master_config['training_config']), train_dataset=pools[treat], data_collator=lambda b: {'input_ids': tokenizer([f"Instruction:\n{x['instruction']}\n\nResponse:\n{x['response']}" for x in b], truncation=True, padding="max_length", max_length=data_cfg["max_seq_len"], return_tensors="pt")["input_ids"], 'labels': tokenizer([f"Instruction:\n{x['instruction']}\n\nResponse:\n{x['response']}" for x in b], truncation=True, padding="max_length", max_length=data_cfg["max_seq_len"], return_tensors="pt")["input_ids"]}); trainer.train(); plot_training_history(trainer.state.log_history, run_id, run_dir); peft_model.eval(); ScientificLoTSuite(peft_model, tokenizer, os.path.join(run_dir, "LoT_Analysis")).run_full_analysis(master_config['lot_config'], full_ds)
            results.append({"Run": run_id, "Treatment": treat, "Method": method, "RLCT": rlct_val, "PPL": math.exp(np.mean([peft_model(**tokenizer(f"{x['instruction']}\n{x['response']}", return_tensors='pt', truncation=True, max_length=128).to(run_cfg['device']), labels=tokenizer(f"{x['instruction']}\n{x['response']}", return_tensors='pt', truncation=True, max_length=128).to(run_cfg['device']).input_ids).loss.item() for x in full_ds.shuffle(seed=123).select(range(min(20, len(full_ds))))]))}); del peft_model, trainer; gc.collect(); torch.cuda.empty_cache()
    with pd.ExcelWriter(os.path.join(output_dir, "FINAL_RESULTS.xlsx"), engine='xlsxwriter') as w: pd.DataFrame(results).to_excel(w, sheet_name='Main', index=False); (pd.concat(all_rlct).to_excel(w, sheet_name='RLCT_Loss', index=False) if all_rlct else None)
    doc_gen.generate_all(); dest = os.path.join(BASE_DRIVE_PATH, f"Results_{run_cfg['experiment_name']}"); shutil.copytree(output_dir, dest, dirs_exist_ok=True) if os.path.exists(BASE_DRIVE_PATH) else print(f"\nSaved locally: {output_dir}")
print(f"STARTING EXPERIMENT: {ACTIVE_CONFIG['run_config']['experiment_name']}"); run_linguistic_anova_experiment(ACTIVE_CONFIG)

C:\Users\Usuario\AppData\Roaming\Python\Python314\site-packages\confection\__init__.py:38: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1 import BaseModel, Extra, ValidationError, create_model

ConfigError: unable to infer type for attribute "REGEX"